### ISSUE TITLE
Make docker image smaller

### ISSUE THREAD

**Issue by nickdoikov** [yyyar/gobetween#10]
Need to switch from centos7 base image to https://hub.docker.com/_/alpine/
Image will be much smaller (5 mb base image)

**Comment by yyyar** [comment]
@nickdoikov  is it something you're still going to work on?

**Comment by nickdoikov** [comment]
yes, but we will faced with possible exec discovery/checks problems due a tiny userspace on this containers.

**Comment by nickdoikov** [comment]
ticket closed  and will be opened later if someone will be interested in small images
