### ISSUE TITLE
[feature request] Support proxy protocol

### ISSUE THREAD

**Issue by thetechnick** [yyyar/gobetween#100]
I am experimenting with replacing haproxy with gobetween as TCP/UDP lb in front of a kubernetes cluster.
For most of my deployments the preservation of the client IP is mandatory for logging/auditing and rate limiting on application level.

To preserve the client IP I currently use proxy protocol terminated at the kubernetes ingress controller (nginx).
https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

Proxy Protocol is implemented by:
- HAProxy
- AWS ELB
- Nginx

So I want to ask if it is possible to include support for proxy protocol in gobetween.
After doing a quick scan through the code base I think it would be very simple to add the header information to the connection handling about here:
https://github.com/thetechnick/gobetween/blob/master/src/server/tcp/server.go#L345

**Comment by yyyar** [comment]
Done as #101
