### ISSUE TITLE
Migrate from github.com/lxc/lxd to github.com/lxc/lxd/client dependency

### ISSUE THREAD

**Issue by illarion** [yyyar/gobetween#103]
@jtopjian could you please investigate ? They've moved lxd client functionality to a separate package, so that gobetween is no more buildable, and simply changing dependency doesn't help -- they've rewritten client API.

https://github.com/lxc/lxd/issues/3666

**Comment by jtopjian** [comment]
@illarion I submitted a fix for this two weeks ago: #102
