### ISSUE TITLE
Provide FROM_SCRATCH container

### ISSUE THREAD

**Issue by drasko** [yyyar/gobetween#106]
CentOS container is huge. It would be good to provide tiny `FROM_SCRATCH` image, as Traefik is doing now:

https://hub.docker.com/_/traefik/

https://github.com/containous/traefik-library-image/blob/57f83af9d2719e5f25e6c769fd2640f973b519dc/scratch/arm64/Dockerfile

**Comment by klud1** [comment]
This would be a really nice improvement, since it will lower the image footprint.
One more thing, it'd be great to have ARMv*  Images as well.

**Comment by klud1** [comment]
If any repo owner agrees on this, I could eventually open a PR

**Comment by hirikarate** [comment]
Meanwhile, I have made a custom build for myself based on Alpine image, which is tiny and well-supported.

1. Firstly, we need to build gobetween for Alpine environment
   - `git clone https://github.com/yyyar/gobetween.git`
   - `cd ./gobetween`
   - Create a file named "Dockercompile": `vi ./Dockercompile`
   ```
   FROM golang:1.9.0-alpine3.6
   RUN apk add --update make git g++ gcc 
   VOLUME /go/src/app
   WORKDIR /go/src/app
   CMD make deps && make run
   ```
   - Create new image: `docker build -f ./Dockercompile -t gobetweencompile .` (notice the last dot `.`)
   - Run a container: `docker run -v ./:/go/src/app gobetweencompile`

2. Look at your folder `./gobetween/bin`, there should be a single file named `gobetween` right now.
3. Build the useable gobetween image:
   - Edit the original Docker file `vi ./Dockerfile`
   ```
   FROM alpine:3.6
   COPY bin/gobetween  /usr/bin/
   VOLUME /etc/gobetween/conf
   CMD ["/usr/bin/gobetween", "-c", "/etc/gobetween/conf/gobetween.toml"]
   ```
   - Create the image: `docker build -t gobetween:0.5.0-alpine .`
4. Clean up by removing the compile image: `docker image rm gobetweencompile`
5. Now you have a tiny gobetween image ready to use. Check it out: `docker image ls`

@klud1 How can I send a PR to you?

**Comment by nickdoikov** [comment]
https://github.com/yyyar/gobetween/blob/61786d5c2b47742c67131b3365ddb9d200e90378/Dockerfile#L1-L3

i decided do not hardcode config mounting path  , it is up to end user. 
a little bit later i will get rid from config hardcode and will use a env variables in Dockerfile

**Comment by klud1** [comment]
In addition, the whole building process could be done on docker images and/or be added as an alternative process in the Makefile.

**Comment by yyyar** [comment]
Merged to master @nickdoikov please verify
