### ISSUE TITLE
Ability to drain/shutdown a particular backend using API

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#118]
Would it be possibly to put a particular backend server (IP:PORT combination) in **drain** mode using the REST API?
 
In the "drain" mode, Gobetween would stop sending *new* traffic to the backend server, but let the existing connections finish.

The "drain" API could possibly also have a **wait timeout**, after which, the existing connections are forcibly killed.

My use case is the following:
In a rolling upgrade scenario of backend servers, I need to handle *existing connections* gracefully.
i.e. wait for the existing connections to finish and not have the clients see a disconnect.
I use Consul for the backend server discovery.

My client connections would be all short-lived (a few minutes), so having a configurable timeout would be great (if possible).

Regards,
Shantanu Gadgil

**Comment by yyyar** [comment]
It's nice feature to have. It also makes sense to generalize it and allow actions on backends.

```
DELETE /servers/<name>/backends/12.3.2.1:1231
Instantly removes backend, forcefully dropping all connections
```

```
POST /servers/<name>/backends
{
    host: "host",
    port: "port",
    weight: 1,
    ....
 
}
```

```
POST /servers/<name>/backends/12.3.2.1:1231
{
    action: "drain",
    options: {
        timeout: "10m"
    }
}
```

But here important questions arises. How to handle this situation when backends list is not 'static' list and discovered via docker, or other discovery type? If backend will dissapear from discovery and then appear again, all it's properties will be refreshed.

**Comment by shantanugadgil** [comment]
The question about non-static list is very important. 👍 
My "Docker Orchestrator" is Nomad, so there could very easily be multiple dockers for the same service running on a single/different machines.

**Comment by nickdoikov** [comment]
Sure we leave "non-graceful"  in place because if someone using "long " persistent connections - draining can take infinite time to be completed %)
