### ISSUE TITLE
Headers in TLS termination

### ISSUE THREAD

**Issue by PlkMarudny** [yyyar/gobetween#122]
When TLS termination is used, HTTP GET request receives following headers:

    Accept-Ranges -> bytes
    Cache-Control -> no-cache, private, max-age=0
    Content-Length -> 690
    Content-Type -> image/png
    Date -> Thu, 11 Jan 2018 13:16:55 GMT
    Expires ->Thu, 01 Jan 1970 04:00:00 +04
    Last-Modified ->Thu, 23 Nov 2017 12:48:34 GMT
    Pragma -> no-cache
    Vary -> Origin
    X-Accel-Expires -> 0

But I would like to enable caching on some objects (images, for example). Is there any way to achieve that?

**Comment by yyyar** [comment]
Hi @PlkMarudny 
gobetween works on TCP/UDP (L4) level so it does not know anything about data passing inside connection, hence can't modify HTTP headers. We're planning add HTTP support in future releases.

Currently you need to enable caching on your backend server so it will set all headers that you need.

**Comment by nickdoikov** [comment]
Closed
