### ISSUE TITLE
howto enable PROXY protocol only for some backends

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#124]
@thetechnick @yyyar @nickdoikov 

I am using Gobetween 0.5.0 configured with SNI enabled.
I use Consul for discovery.
I have a single listener on **443** and many backends which are reached based on the SNI field.

Using this as reference: https://github.com/yyyar/gobetween/wiki/Proxy-Protocol

My understanding is that the PROXY protocol will get enabled for all backends for a single listener.

Is it possible via Consul discovery to have PROXY enabled only for a few backends and **not** all ?

This is similar to HAProxy's behavior where it can optionally append the directive **send-proxy** only to the required backends?

Regards,
Shantanu

**Comment by yyyar** [comment]
Hi @shantanugadgil
Yep currently is gets enabled for all backends. Enabling it only for a some backends with directive requires some coding :-) Do you still need this feature?

**Comment by shantanugadgil** [comment]
Hi, yes, it would be a great enhancement to have it per service.
For now I am making do with PROXY disabled for all.

**Comment by shantanugadgil** [comment]
closing due to age
