### ISSUE TITLE
Is there a Web UI for GoBetween?

### ISSUE THREAD

**Issue by c0fe** [yyyar/gobetween#126]
Is there a Web UI for GoBetween so instead of having to mess around with config files for management and configuration?

**Comment by shantanugadgil** [comment]
No, not yet.

**Comment by c0fe** [comment]
Is there an API available that I can get my interface to communicate with?

**Comment by shantanugadgil** [comment]
https://github.com/yyyar/gobetween/wiki/REST-API

HTH,
Shantanu

**Comment by yyyar** [comment]
Actually there was a development of Web GUI: https://github.com/kikom/gobetween-ui
We planned to include it in release when it will be fully finished.

@kikom please advice on how it can be set up.

**Comment by c0fe** [comment]
Is this dead?

**Comment by nickdoikov** [comment]
No , i `m using  it in many prod env`s . 
I will ask Gene(@kikom ) to add manuals and description.

**Comment by avelino** [comment]
I think this issue can be closed
duplicated: https://github.com/yyyar/gobetween/issues/8
initial project: https://github.com/kikom/gobetween-ui (ref https://github.com/yyyar/gobetween/issues/126#issuecomment-361655148)

**Comment by nickdoikov** [comment]
Issue closed
