### ISSUE TITLE
Can add sticky session strategy?

### ISSUE THREAD

**Issue by joeke80215** [yyyar/gobetween#136]
Can add sticky session strategy?

Thanks

**Comment by nickdoikov** [comment]
Hello, @joeke80215  , for L4 load balancing (Gobetween is a L4 balancer for now) you can use iphash strategy - it is a only option that can allow you to route requests from some ip to same backend out of one tcp session scope.

please read :
[https://github.com/yyyar/gobetween/wiki/Balancing#iphash](url)

**Comment by shantanugadgil** [comment]
hi @nickdoikov  clicking the link doesn't work, copy pasting it works. 😕
