### ISSUE TITLE
Delete servers over API but scheduler is still running

### ISSUE THREAD

**Issue by manhnguyenduc** [yyyar/gobetween#140]
My config .toml
 

> [servers.EEz6WJtu_rotate]
>     max_connections = 0
>     client_idle_timeout = "0"
>     backend_idle_timeout = "0"
>     backend_connection_timeout = "0"
>     bind = "0.0.0.0:55001"
>     protocol = "tcp"
>     balance = "weight"
>     [servers.EEz6WJtu_rotate.discovery]
>       kind = "json"
>       failpolicy = "keeplast"
>       interval = "2m"
>       timeout = "10s"
>       **json_endpoint = "http://127.0.0.1/pool/rotate/EEz6WJtu"**
>       json_host_pattern = "host"
>       json_port_pattern = "port"
>       json_weight_pattern = "weight"
>       json_priority_pattern = "priority"
>       json_sni_pattern = "sni"
>     [servers.EEz6WJtu_rotate.healthcheck]
>       kind = "ping"
>       interval = "2s"
>       passes = 1
>       fails = 1
>       timeout = "1s"
> 

There is log when delete
> 

> 2018-04-26 00:32:05 [INFO ] (server.Listen): Stopping EEz6WJtu_random
> 2018-04-26 00:32:05 [INFO ] (scheduler): Stopping scheduler
> 2018-04-26 00:32:05 [ERROR] (server.Listen): accept tcp [::]:63004: use of closed network connection
**> 2018-04-26 00:32:05 [INFO ] (server.Listen): Stopping EEz6WJtu_rotate**
> 2018-04-26 00:32:05 [INFO ] (scheduler): Stopping scheduler
> 2018-04-26 00:32:05 [ERROR] (server.Listen): accept tcp [::]:55001: use of closed network connection
> **2018-04-26 00:33:22 [INFO ] (jsonFetch): fetching http://127.0.0.1/pool/rotate/EEz6WJtu**
> 2018-04-26 00:33:22 [INFO ] (jsonFetch): []

jsonFetch still retrieves the data despite deleting the server

**Comment by yyyar** [comment]
Fixed, will be released as part of 0.8.0
