### ISSUE TITLE
Windows Service / Installer

### ISSUE THREAD

**Issue by keslabs** [yyyar/gobetween#141]
Perhaps I've missed it, but is there a method to install in as a service on Windows? I've attempted several different ways but it won't remain running.

To the contributors: Thanks for the hard work. This is a beautifully simple architecture... love the straightforward configuration style.

**Comment by shantanugadgil** [comment]
There is a tool called nssm (https://nssm.cc/) which can be used to make services from standalone binaries.

I use it for tools like Consul and Nomad on Windows.

Maybe that could help?

Regards,
Shantanu

**Comment by keslabs** [comment]
I'll give that a shot and respond back with the outcome. Thanks.

**Comment by keslabs** [comment]
It worked well. Perhaps a small note included on the windows installation page would be in order?

Thanks again for the help!
