### ISSUE TITLE
Different farms TCP / UDP on same ip/port unable to bind to address

### ISSUE THREAD

**Issue by snowbash** [yyyar/gobetween#142]
Hi,

Configuring two farms usign the same ip/port but different protocols, one TCP the other UDP produces a bind() error - address already in use.

This should be allowable 

Thanks

Jason

**Comment by illarion** [comment]
@snowbash , could you please give us your config and log with error?

**Comment by illarion** [comment]
@snowbash I have just tried and it works, so it should be something with your config
