### ISSUE TITLE
WAF plugin

### ISSUE THREAD

**Issue by wiseflat** [yyyar/gobetween#143]
Hi,

I use to deploy haproxy as a reverse proxy and I am trying to set up haproxy + naxsi WAF. [Link](https://www.haproxy.com/blog/high-performance-waf-platform-with-naxsi-and-haproxy/)
I have just discovered gobetween and I like the LXD service discovery, the REST API, so I will give it a try 👍 

I was wondering if it's possible to make this combination:

```
WAN <> gobetween |<-> [ WAF ] (nginx-naxsi or something else as a primary backend)
		 |-> backend1 (webapp)
		 |-> backend2 (webapp)
```

Is it possible to add modsecurity or naxsi as a transparent WAF to gobetween ? 

Cheers

**Comment by nickdoikov** [comment]
i`m not sure that it is possible at all on a L4 balancing level .
