### ISSUE TITLE
https request via gobetween

### ISSUE THREAD

**Issue by gaurav611** [yyyar/gobetween#147]
Hi All, 

Not sure if this is right platform for such query but I am trying to use gobetween for an application with two webservers running https application.

On the third node I have installed the gobetween and using the below configuration.

[servers.new]
protocol = "tcp"
bind = "host3:443"

  [servers.new.discovery]
  kind = "static"
  static_list = [
      "host1:443",
      "host2:443"
  ]

I am able to access the application using the gobetween (host3) url and able to login, however I am facing the issue with a particular section where flash has to be loaded. It is loading without any issue where flash is not required.

Should I go with TLS for https requests? whihc one **"servers.default.backends_tls"** or **"servers.default.tls"**

Regards, 
Gaurav

**Comment by nickdoikov** [comment]
Hello  @gaurav611, try to use balancing policy balance = "iphash"
in general you should not faced with any issue on l4 balancing level except that each granular request can pass to different backend.

**Comment by gaurav611** [comment]
Hello @nickdoikov & All

It was working fine after the changes as per your suggestion but today I am getting below error when I completely shut down application on active node.

dial tcp x.x.x.x:443: connectex: No connection could be made because the
target machine actively refused it.

Thanks, 
Gaurav

**Comment by gaurav611** [comment]
Yes, heath check is not configured, but the below (document reference), does it check for ICMP ping to the host or it checks for the port? As IP of both the application servers will always be reachable so just ping may not work.

[servers.default.healthcheck]
kind = "ping"
interval = "2s"
ping_timeout_duration = "500ms"

Do you suggest to use the "exec_command " option to check the active node ?

Regards. 
Gaurav

**Comment by nickdoikov** [comment]
Ping check operate by   checking port by tcp ping , if your app will not respond on trying to open tcp connection - backend will be marked faulty after defined retry quantity
you can also use some script instead. 

for now gb is not imagine does your backends ok or not , that`s why you have got such errors.

**Comment by nickdoikov** [comment]
closed

**Comment by gaurav611** [comment]
Thanks a lot for the quick replies!! It is working perfectly after adding health check.
