### ISSUE TITLE
FTP Extended Passive (EPSV) through gobetween

### ISSUE THREAD

**Issue by Paulus88** [yyyar/gobetween#160]
Hi Guys,

Maybe this is not an issue but just my knowledge of loadbalancers, I use gobetween for our FTP solution, it works awesome for Passive and Active DATA connections but am running into a little difficulty with Extended Passive.

The difference between Extended Passive and Passive is that Passive receives its DATA ports straight from the FTP server that gobetween has selected for the users FTP client.
Authentication
FTP Client - 21 -> Loadbalancer - 1021 -> FTP Server
Data
FTP Client - PASV -> FTP Server

Extended Passive tries to get its DATA ports from the same location that it connected to in the first place (in this case, the gobetween server).
Authentication
FTP Client - 21 -> Loadbalancer - 1021 -> FTP Server
Data
FTP Client - EPSV -> Loadbalancer (Were is my data Mr loadbalancer? xD)

I have tried port forwarding the data ports straight through the Loadbalancer to the FTP Servers using Windows netsh, but that did not help.

There are only about 2 Linux FTP clients that are using Extended Passive as the default way of receiving data but I believe that IPv6 EPSV is going to become a lot more popular way of transferring data.

Do you guys have any idea or am I doing something wrong?

**Comment by illarion** [comment]
@Paulus88 EPSV and PASSIVE modes involve logic on L7(application) level -- server sends host and port back to client (in EPSV it sends just port), so that it is currently impossible to implement this in L4 loadbalancer, such as gobetween, without parsing the server response and implementing part of ftp protocol. 

Could you describe your use case? How big is your production setup? What are you trying to achieve with help of gb?

**Comment by Paulus88** [comment]
@illarion thanks for the reply and the clear information.
In our situation Passive does seem to work with the L4, the client asks the last location for it's Passive port's and that is the FTP server.

This is the solution that we use with the gobetween loadbalancer:
http://www.serv-u.com/kb/2103/How-to-Deploy-ServU-Gateway-in-a-Cluster
`<img src="http://www.rhinosoft.com/kbase/kbimages/KB2103_MFT_Cluster.png">`

I like gobetween because it's easy to manage but being a Layer 4 it does miss some possibilities.
Would you recommend anything to be able to send an FTP server response using gobetween?

**Comment by Paulus88** [comment]
Hi Guys,

Reply from SolarWinds, (Serv-U):
_"The saw that the EPSV doesn’t work with load balancer (LB) because for data transfer connection, it should to know the port and IP (in EPSV mode, server only sends port). So, client doesn't know to which host should connect for data transfer. It is impossible with LB configuration."_

So the conclusion is that it is impossible to make EPSV work behind a loadbalancer.

You can close this case and thanks for your time and help :)
