### ISSUE TITLE
does the gobetween support as a daemon process and support specify user account as Haproxy

### ISSUE THREAD

**Issue by zhanyonm** [yyyar/gobetween#162]
I run the gobetween as UDP loadbalance with the 0.5 release and find that:
it doesn't support to run as a daemon process.
And it can't be run successful with non-root account because of the error:
[ERROR] (udp/server): Error starting UDP server: listen udp 10.212.1.103:1000: bind: permission denied

so Could you tell me?
dose it support this feature? if yes, how should I configure it?
if not, is there any plan to add these feature? As you know, we should not run the network services with root account because of security reason.

thanks in advance.

**Comment by shantanugadgil** [comment]
I think you can achieve the same if you run gobetween as a system service (systemd/upstart)

You can also add the relevant network capability to run it as non-root, yet be able to bind to port < 1024

BTW, what OS and version do you run gobetween on?

**Comment by nickdoikov** [comment]
Hello @zhanyonm 
seems like you tried to run GB from non-privileged user , so it can't bind on needed port.
this is not related to a GB itself , but it rather related to a os security restrictions.
you can create systemd unit and run GB from root (just an example)

Example systemd unit :

gobetween.service
```
[Unit]
Description=Gobetween
Documentation=https://github.com/yyyar/gobetween
After=syslog.target
After=network.target

[Service]
ExecStart=/gobetween/gobetween -c /gobetween/config/gobetween.toml
WorkingDirectory=/gobetween
LimitNOFILE=30000
Restart=always
StandardOutput=journal
StandardError=inherit
User=root
Group=root

[Install]
WantedBy=multi-user.target
```

you can place it into /lib/systemd/system/

also you can enable it with command
```
sudo systemctl enable gobetween.service
sudo systemctl start obetween.service
```

**Comment by shantanugadgil** [comment]
Hi,

I think @zhanyonm wanted to run gobetween as a non-root user.
I was hinting at something like:
https://github.com/fabiolb/fabio/wiki/Binding-to-Low-Ports

Specifically the "capabilities" part:
```
AmbientCapabilities=CAP_NET_BIND_SERVICE
```

Hope that helps,
Regards,
Shantanu

**Comment by zhanyonm** [comment]
@all, thanks again for your reply.
the OS used is Linux vyos 3.13.11-1-amd64-vyos ( kenerl 3.13 and VyOS 1.1.7).
yes,  I can try it as  system service .  there is a requirement that the LB will be updated ( add/remove server) dynamically in my project. under this case, if removing/adding a backend from/to a GB server with configure file, will other servers be out of service during reload/restart GB service? 
currently I run a GB process with different configure file per LB GB server. it means there are multi GB processes at same time for different LB servers with different configure file.
if one server modified, I just kill the corresponding process and restart a new process with the new configure file. there is the mail reason that the system service doesn't be used. please inform me if I'm wrong.
For the special requirement (non-root, modify dynamically and no impact on other LB servers), are there more better solutions?


ps: for the GB 0,5 release, it will panic if run multi GB process with same udp configure. the second will bind udp port fail and panic.


vyos@vyos:~$ sudo /opt/vyatta/sbin/gobetween -c /home/vyos/zvr/lb/conf/lb-94d827d2c1cc48bfadf6bb9b3dc12d0e-listener-83f84c723581448b8e0f17955e733c90.cfg
gobetween v0.5.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xad3906]

goroutine 20 [running]:
_/home/yyyar/workspace/gobetween/src/server/udp.(*Server).Stop(0xc4202180e0)
        /home/yyyar/workspace/gobetween/src/server/udp/server.go:313 +0xe6
_/home/yyyar/workspace/gobetween/src/server/udp.(*Server).Start(0xc4202180e0, 0x20, 0xc4201a3980)
        /home/yyyar/workspace/gobetween/src/server/udp/server.go:134 +0xa7
_/home/yyyar/workspace/gobetween/src/manager.Create(0xc4202480bf, 0x20, 0xc4201a3980, 0xc420258170, 0xc420258190, 0xc4202581b0, 0xc4201f4c80, 0x11, 0xc4201a3080, 0x3, ...)
        /home/yyyar/workspace/gobetween/src/manager/manager.go:133 +0x331
_/home/yyyar/workspace/gobetween/src/manager.Initialize(0xc4201a3010, 0x4, 0xc42020ad00, 0x37, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/yyyar/workspace/gobetween/src/manager/manager.go:49 +0x245
created by main.main.func1
        /home/yyyar/workspace/gobetween/src/main.go:78 +0xde

I can submit an issue to record this if it is not an issue known. I read the master latest code, it maybe fixed because of the udp part has been enhanced.

**Comment by illarion** [comment]
@zhanyonm I've checked it right now on 0.6.0 and got no panic, but error instead:

2018-08-21 14:23:22 [FATAL] (manager): Could not start listening UDP: Failed to create listening udp socket: listen udp 127.0.0.1:4000: bind: address already in use

**Comment by zhanyonm** [comment]
@illarion  yes 0.6 has fixed this panic issue.

**Comment by illarion** [comment]
@zhanyonm is it ok now? Can I close the issue?
