### ISSUE TITLE
tftp get/put file fail 

### ISSUE THREAD

**Issue by zhanyonm** [yyyar/gobetween#168]
hi all:
as we know tftp is a classical udp application. I setup a tftp server in backends servers.
when the tftp gets file fail from GB lb.
I capture packets and analyze them. when backend receives the tftp cmd and reply it with a new source port and GB/LB will drop this packet and send ICMP error msg (unreachable port).

how the GB handle this case? 
thanks very much!
(gobetween v0.6.0)

**Comment by illarion** [comment]
@zhanyonm I found a way to do it. It is new functionality. In worst case it will be in 0.7 release. If it will be easy and I'll have enough time, will be sooner in 0.6.1 or 0.6.x

**Comment by zhanyonm** [comment]
@illarion I'm glad to hear it. 
please inform me when it is fixed. 
thanks very much.

**Comment by cthayer** [comment]
I can confirm that TFTP servers behind a GB/LB still do not work in the 0.7.0 release

**Comment by illarion** [comment]
@zhanyonm I've digged into TFTP documentation and found that my previous solution is not going to work on currently L4 level of proxying udp packets back and forth. The only possible way is to implement separate kind of server.protocol = "tftp", which is out of scope of our plans for now. Unfortunately, I have to close this issue and say sorry for inconvenience.
