### ISSUE TITLE
Access rules does not work, as expected

### ISSUE THREAD

**Issue by olih10200** [yyyar/gobetween#169]
Hi,

I use this access-control
```
    [servers.bigtable.access]
        default = "deny"
        rules = [
            "allow 10.128.0.0/32",
            "allow 127.0.0.1",
            "allow 10.7.0.0/16",
        ]
```
But many `Client disallowed to connect 10.128.0.5:nnnnn` come from debug lines.

(gobetween v0.6.0)

**Comment by nickdoikov** [comment]
hello @olih10200 
 you have used a wrong mask 
```10.128.0.0/32```
that equal to : 
```  
10.128.0.0/255.255.255.255
```

in case you want to open  10.128.0.N sunbnet (where the N  is any ip from 1-254 ranage) 
you can use such mask:
```
10.128.0.0/24
```

You can use netmask  calculator in case you are not familiar with netmasks:

```
http://jodies.de/ipcalc
```
