### ISSUE TITLE
docker image 0.6.0 is not working (dynamic executable)

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#170]
@nickdoikov @yyyar @illarion 

The latest docker image `0.6.0` from docker hub is not working:

```
# docker run --name dummy060 yyyar/gobetween:0.6.0 /usr/bin/gobetween --version
Unable to find image 'yyyar/gobetween:0.6.0' locally
0.6.0: Pulling from yyyar/gobetween
df1b5fba0773: Pull complete
Digest: sha256:507931fb4378b22a10747500b31867135501ff08d05f459666993cd353fd682b
Status: Downloaded newer image for yyyar/gobetween:0.6.0
standard_init_linux.go:190: exec user process caused "no such file or directory"

# docker run --name dummy050 yyyar/gobetween:0.5.0 /usr/bin/gobetween --version
Unable to find image 'yyyar/gobetween:0.5.0' locally
0.5.0: Pulling from yyyar/gobetween
049532911afd: Pull complete
Digest: sha256:b2759c1cb43ae31ca389587822b386c6d313d1086915b48dcf604e3ddc318b1c
Status: Downloaded newer image for yyyar/gobetween:0.5.0
gobetween v0.5.0
0.5.0
```

Upon deeper investigation, I see that the binary inside the 0.6.0 image is a **dynamic executable**,
The binary inside the 0.5.0 image is a **static executable**.

Thoughts:
For want of size, can the dockerized build be just an Alpine build rather than striving for a static binary.

I'll try to cook up something during the day.

Regards,
Shantanu 

related to issue #166

**Comment by nickdoikov** [comment]
@shantanugadgil  thanks !
i have found a problem in makefile, new container will be released soon.

**Comment by nickdoikov** [comment]
https://github.com/yyyar/gobetween/pull/171

**Comment by nickdoikov** [comment]
after changes : 
```
$ ldd gobetween
	not a dynamic executable
```

@shantanugadgil 
feel free to re-pool both containers latest and 0.6.0

ticket closed
