### ISSUE TITLE
[feature request] implement SSL checker/prober within gobetween

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#173]
Hi,

The feature request may seem obscure, but let me explain my use case:

I use `gobetween` in the "Docker" format.
As gobetween is now `FROM scratch`, there is nothing else inside the container.
I use Consul for discovery + healthchecks, and Nomad to launch the docker.
Consul doesn't natively support a "TCP + SSL + SNI" health check, so I have cobbled together the following to achieve it.
https://github.com/shantanugadgil/sslchecker/blob/master/main.go

(Consul supports "script" based health checks which is what I would use with a separate binary)

Recently I have been facing the issue with GB that it "hangs" (accepts connection, but doesn't forward it)
https://github.com/yyyar/gobetween/issues/172

My requirement is to have this "SSL checking" functionality as part of GB itself so that I don't have to include another binary in the container.

If gobetween has the functionality inbuilt it would be awesome, otherwise I would have to build another a "gobetween + sslchecker" container.

Thanks and Regards,
Shantanu

**Comment by illarion** [comment]
@shantanugadgil #172 was caused by gobetween side, before attempting to forward connection. We already have half of your requirement implemented in https://github.com/yyyar/gobetween/wiki/Healthchecks#probe . The missing part is tls protocol in probe.

**Comment by illarion** [comment]
@shantanugadgil could you please take a look at branch feat-tls-probe-#173 ? It has the same user experience as `probe` healthcheck, but supports `tls` protocol. It is extremely simplistic, so that no tls configuration is possible, but flexible payload is supported. 

Thank you
