### ISSUE TITLE
Improve UDP performance

### ISSUE THREAD

**Issue by zhanyonm** [yyyar/gobetween#177]
I do a test about UDP and find the result not so good with iperf.
the testbed is 4core cpu, 4G memory vm and the transfer upload bandwidth is about 50M bps.
at the same testbed, ipvs is about 150M bps and haproxy tcp about 450M bps. FYI。

**Comment by illarion** [comment]
Should be retested after #180 will be merged

**Comment by zhanyonm** [comment]
@illarion thanks for your effort. i will do the test after it's ready.

**Comment by illarion** [comment]
@zhanyonm please reply, your efforts are valuable for the project

**Comment by illarion** [comment]
@zhanyonm thank you for testing! it's not perfect yet, but 10% improvement is better that 0 or performance degradation. We will work on it to improve it more.

**Comment by zhanyonm** [comment]
the testbed is 8 cpu,8G memory. the 6.0 upload data: "tx_second": 8461000,  6.1 release:   "tx_second": 9357500,

the detail data:
6.0:
{
    "active_connections": 0,
    "rx_total": 26095338,
    "tx_total": 3280182000,
    "rx_second": 76761,
    "tx_second": 8461000,
    "backends": [
        {
            "host": "192.168.2.246",
            "port": "5000",
            "priority": 1,
            "weight": 1,
            "stats": {
                "live": true,
                "discovered": true,
                "total_connections": 2,
                "active_connections": 1,
                "refused_connections": 0,
                "rx": 25941978,
                "tx": 3263352000,
                "rx_second": 77179,
                "tx_second": 10714000
            }
        }
    ]

6.1:
{
    "active_connections": 0,
    "rx_total": 17142354,
    "tx_total": 1713630000,
    "rx_second": 104584,
    "tx_second": 9357500,
    "backends": [
        {
            "host": "192.168.2.246",
            "port": "5000",
            "priority": 1,
            "weight": 1,
            "stats": {
                "live": true,
                "discovered": true,
                "total_connections": 1,
                "active_connections": 1,
                "refused_connections": 0,
                "rx": 17149428,
                "tx": 1713630000,
                "rx_second": 108000,
                "tx_second": 9318000
            }
        }
    ]

**Comment by zhanyonm** [comment]
yes, the result means that we're on the right road. thanks for your effort.

**Comment by zhanyonm** [comment]
@illarion are there any plan or roadmap for this point? As you know, the performance is a very important point for LB.

**Comment by illarion** [comment]
@zhanyonm roadmap is "as soon as possible". I am going to perform benchmarks and then we will release 0.7.0 with improved udp performance and few other fixes and features, postponing all the rest to future releases

**Comment by illarion** [comment]
@zhanyonm could you please provide your config for tests, so that I could replicate it?

**Comment by illarion** [comment]
@zhanyonm there is a branch improve-udp-performance-#177 that implemens some speed-ups for udp, could you please test?

**Comment by illarion** [comment]
@zhanyonm with this fix I was able to transfer 817 mbit/s from localhost to localhost on my laptop. Could you please test it with your testbed?

**Comment by SchSeba** [comment]
Hi @illarion can you please post the new test results?

**Comment by cunningwasabi** [comment]
hi guys,
with the changes to session.go in this fix, it looks like you've introduced a bug related to the use of the bufPool.
If you look in here;
> func (s *Session) Write(buf []byte)

you see that you get a full buffersize from the bufPool,
> dup := bufPool.Get().([]byte)

but then only pass the slice to NewSession;
> case s.out <- dup[0:n]:

then, in here:
func NewSession(clientAddr *net.UDPAddr, conn *net.UDPConn, backend core.Backend, scheduler *scheduler.Scheduler, cfg Config) *Session

you return only the slice back to the buff pool
n, err := s.conn.Write(buf)
bufPool.Put(buf)

which means that the bufPool array is now much smaller, and cannot hold as much data for the next use.


One fix that I got working was to pass a struct to the channel.
type sendBufPool struct {
        buf             []byte
        bufsize         int
}
in NewSession;
                        case sendBufPool := <-s.out:
                                n, err := s.backendconn.Write(sendBufPool.buf[0:sendBufPool.bufsize])
                                bufPool.Put(sendBufPool.buf)

I'm sure there are better ways to deal with it, but feel free to have a look at my fork for the full code (will send later today).
