### ISSUE TITLE
Simple load balancing configuration needed

### ISSUE THREAD

**Issue by alpertandogan** [yyyar/gobetween#178]
lbserver:xxx.xxx.xxx.120 port:80 (gobetween running)

Server 1: xxx.xxx.xxx.121   port:80 
Server 2: xxx.xxx.xxx.122   port:80 

Centos 7.5 works gobetween debug mode it pings server1,2 but there is no response from 
browser   http://lbserver

--------------------------------------gobetween.toml-------------------------
[servers]
[servers.sample]
bind = "xxx.xxx.xxx.120:80"
protocol = "tcp" 
balance = "roundrobin"
max_connections = 10000
client_idle_timeout = "10m"
backend_idle_timeout = "10m"
backend_connection_timeout = "2s"

[servers.sample.discovery]
    kind = "static"
    static_list = [
      "xxx.xxx.xxx.121:80 weight=1",
      "xxx.xxx.xxx.122:80 weight=1"
    ]

    [servers.sample.healthcheck]
    fails = 1                      
    passes = 1
    interval = "2s"   
    timeout="1s"             
    kind = "ping"
    ping_timeout_duration = "500ms"
    
    
[servers.udpsample]
bind = "xxx.xxx.xxx.120:80"
protocol = "udp"

  [servers.udpsample.udp]
  max_responses = 1

  [servers.udpsample.discovery]
  kind = "static"
  static_list = [
      "xxx.xxx.xxx.121:80",
      "xxx.xxx.xxx.122:80"
  ]

**Comment by zhanyonm** [comment]
in my opinion, you can check if the iptables/firewall of backend block the tcp packets.

**Comment by alpertandogan** [comment]
Linux 4.1.12-124.18.6.el7uek.x86_64 

I disabled firewall and check again xxx.xxx.122:80   works well but .  lb.server  xxx.xxx.120:80 not work on the same switch .....  on debug output it(gobeetwen) pings two backend server correctle but this lb.server dont response port 80

**Comment by nickdoikov** [comment]
hello @alpertandogan 

try to play with this params.

```
client_idle_timeout = "10m"
backend_idle_timeout = "10m"
backend_connection_timeout = "2s"
```
my opinion - you faced with connection reusage, that`s why you are pointed to a same backend.
this lb is l4 , not a l7  , so in case you want to use it as a web proxy way (request-response-close_connection) you should adjust params to you needs (fast connection close rate).

so  this configuration will be a good start point for you:

```
client_idle_timeout = "2s"
backend_idle_timeout = "2s"
backend_connection_timeout = "2s"
```

also you can enable api and check connection statistics
