### ISSUE TITLE
GB UDP healthcheck not work when one of backend out of service

### ISSUE THREAD

**Issue by zhanyonm** [yyyar/gobetween#179]
the testbed:
client send udp packets to LB with iperf tool and one of backend is out of services: the GB report the error as below

_2018-09-04 14:36:56 [ERROR] (udp/server/session): Failed to read from backend: read udp 9.1.0.1:57631->9.1.0.250:5001: read: connection refused
2018-09-04 14:36:57 [ERROR] (udp/server): Could not write data to UDP 'session' &{0 0 0 {0 0 60000000000 60000000000} {13752770477563286168 1128931549113 0x15f4340} 0xc42057ce10 0xc4201e2018 {{9.1.0.250 5001} 1 1  {true true 117 0 0 0 4519171020 0 9913680}} 0xc420208c30}: Could not write data to udp connection: write udp 9.1.0.1:47079->9.1.0.250:5001: write: connection refused
2018-09-04 14:36:58 [ERROR] (udp/server/session): Failed to read from backend: read udp 9.1.0.1:47079->9.1.0.250:5001: read: connection refused_

because the BG just supports the customize script for healthcheck,  so I write a script and do the health check with nc tool.

when one of backends is out of service and its udp port closed. when it receives the udp packets from GB and response the ICMP error packets (dest port unreachable) to GB. there is so much ICMP packets that there is no ICMP error message  to send when the backend receives the nc health check packets. this results the healthheck ok (nc tool will report ok if it doesn't receive the ICMP error mesage) and the BG still forward the traffic to this bad backend and can not switch to other backend.

so in my opinion, when GB forward traffic fail and receives the ICMP  dest port unreachable error message, it should do something to avoid this issue.
what do you think?

if there is other good solution for udp healthcheck, please tell me. thanks!

**Comment by kometchtech** [comment]
Although it may not have a direct relationship, if you dockernize it, you can create it with a scratch image if it is a gobetween simplex, but for udp healthcheck it is slightly inefficient to create with other images.

In gobetween, can I make a healthcheck with inquiries by SRV records etc.?

**Comment by Joshigangadharan** [comment]
hi @zhanyonm can you please share a template for writing custom healthcheck script for UDP 53. Thanks much.

**Comment by zhanyonm** [comment]
@Joshigangadharan I'm sorry to response so late.
this is a demo script for health check:
#!/bin/sh
# remove it as healthcheck.sh and put it the location you want

if [ $# -ne 2 ];then
  echo "Usage: $0 <ip address> <port>"
  exit 1
fi

line=`ping $1 -c 1 -s 1 -W 1| egrep "100% packet loss"| wc -l`

if [ "$line" != "0"  ];then
  #echo "$1 no response, please check the host & firewall rule!"
  echo -n "fail"
  exit 0
fi

ret=`/bin/nc -unvz -w 1 $1 $2 2>&1 | egrep 'open'& > /dev/null`
if [ $? -ne 0 ] || [ "$ret" = "" ]; then
  echo -n "fail"
else
  echo -n "success"
fi
exit 0
