### ISSUE TITLE
SNI routing in regexp mode allows invalid SNI to go through

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#184]
Hi,

I am using GB built from the branch `attempt-to-fix-#172`. I am observing something weird.
The observation is that even if the SNI field is NOT correct the connections are going to the backend.

Tags in the job in Consul
```
tags = ["sni=backend1.example.com|somethingelse-backend1.example.com"]
```

command to test which backend the connection is going to:
```
openssl s_client -connect backend1.example.com:443 -servername somethingelse-Zbackend1.example.com </dev/null >/dev/null
```

Notice the extra **Z** in the openssl command line.

I have the above openssl cmd in a while loop and looking and GB logs shows that the connection is always forwarded to the correct "backend1" as long as I put anything **before** `backend1.example.com`

My relevant GB config bits are:
```

[servers.backend1]
protocol = "tcp"
bind = ":443"
sni_enabled = true

[servers.backend1.sni]
enabled = true
read_timeout = "10s"
hostname_matching_strategy = "regexp"
unexpected_hostname_strategy = "reject"

[servers.backend1.discovery]
kind = "consul"
failpolicy = "setempty"
consul_host = "myconsulserver.example.com:8500"
consul_service_name = "backend1asg"
interval = "60s"
timeout = "10s"
consul_service_passing_only = true

[servers.backend1.healthcheck]
kind = "ping"
interval = "60s"
timeout = "10s"
ping_timeout_duration = "5s"
passes = 2
fails = 10
```

My understanding of the "regexp" was that it would be an "exact match" of "A" or "B" when the tag is:
`sni=A|B`

**Comment by illarion** [comment]
It's not a bug, actually your domain name with extra Z letter in it matches the regexp you've provided. The correct regexp for such case would be the following:
`^(backend1.example.com)|(somethingelse-backend1.example.com)$`

If it helps or not please tell me. Thanks

**Comment by shantanugadgil** [comment]
🤦‍♂️ 🤦‍♂️ 

This indeed helps!!!
