### ISSUE TITLE
Let gobetween write it's pidfile and fix Systemd unit file issues

### ISSUE THREAD

**Issue by jr-ps** [yyyar/gobetween#190]
v.0.6.1

The systemd unit file at config/systemd/gobetween.service I believe has three problems:

1. `PIDFile=/run/gobetween.pid` tells systemd to expect the program to create a pidfile there, but gobetween does not.

2. `ExecReload=/bin/kill -s HUP $MAINPID` -- SIGHUP simply shuts down gobetween. Is there supposed to be a signal to reload configuration?

3. `ExecStop=/bin/kill -s QUIT $MAINPID` -- SIGQUIT causes a stack trace to be logged by two goroutines and the process to exit 2. The systemd default SIGTERM shuts down cleanly.

It's also probably a good idea to add `LimitNOFILE=...`, as the default ulimit is usually way too low for an active proxy.

I'd be happy to PR these things if you can confirm they're correct.

**Comment by nickdoikov** [comment]
@jr-ps 
Confirmed,  you are correct.
If you can implement it please follow this action points: 

action points :



1) create cli parameter  for pid (need to implement it  ) ```-pidfile=/pathp/to/pidfile``` . 

2) if this cli param does not specified during start GB - start without pid file same as now.

3) fix systemd unit  as described

**Comment by illarion** [comment]
@nickdoikov seems we have to do it ourselves.

**Comment by yyyar** [comment]
Useful link https://gist.github.com/davidnewhall/3627895a9fc8fa0affbd747183abca39 for writing pid file in golang.
