### ISSUE TITLE
Need clarification how to set number of retries on sending to UDP backend

### ISSUE THREAD

**Issue by AmitBawer** [yyyar/gobetween#192]
I am trying to set up a UDP load balancing with static backend list.
Also have healthcheck script running every 1m. 
Aside to that, is there a re-transmit policy or an option when GB detects that backend is not availbale through its native checks (i.e. before it is detected and failed-over by healthcheck script) ? .

**Comment by nickdoikov** [comment]
Hello , @AmitBawer 
Generic UDP do not allows to be sure that packets reached destination, so ther's no other way to determine it on LB side than healthcheck.

**Comment by AmitBawer** [comment]
Thank you @nickdoikov
