### ISSUE TITLE
Fail-Policy set wrong when protocol is not specified

### ISSUE THREAD

**Issue by kriloleg** [yyyar/gobetween#193]
Hi guys.

Faced the issue, that when try to use SRV discovery type and omit srv_dns_protocol, that should be set to default value according to the documentation there will be messed result when getting service statistic. 
Here are the steps to reproduce:

1. Set discovery configuration, omiting dns_protocol
```
[servers.server.discovery]
failpolicy = "keeplast"
kind = "srv"
srv_lookup_server = "192.20.54.73:53"
srv_lookup_pattern = "server-dev.marathon.mesos."
```
2. Query statistic with API

`curl http://localhost:8888/servers/server`

3. Check response field 'failpolicy'. It sets to the 'tcp' value that is not correct

```
 "discovery": {
        "kind": "srv",
        "failpolicy": "tcp",
        "interval": "0",
        "timeout": "0",
        "srv_lookup_server": "192.20.54.73:53",
        "srv_lookup_pattern": "_server-dev._tcp.marathon.mesos.",
        "srv_dns_protocol": ""
 }
```

Best regards

**Comment by yyyar** [comment]
Fixed
