### ISSUE TITLE
Balancing UDP Tunnel

### ISSUE THREAD

**Issue by marcotuna** [yyyar/gobetween#194]
Hello, I am new to gobetween. Today I tried to Load Balance UDP OpenVPN Traffic and I managed to do it. Here is my configuration:

```
[servers.udpsample]
bind = "0.0.0.0:4000"
protocol = "udp"
balance = "iphash"

  [servers.udpsample.udp]
  max_requests  =  0
  max_responses = 999999

  [servers.udpsample.discovery]
  kind = "static"
  static_list = [
      "XX:1194",
      "XX:1194",
      "XX:1194"
  ]
```

However there are a problem, as you can see I had to set **max_responses = 999999**, setting this to 0 (infinite) would not allow me to launch gobetween, setting this with a lower number the connection would not establish or would drop immediately.

Is there any way I could do a proper configuration? I know udp's are tricky.
Thanks!

**Comment by illarion** [comment]
As described in doc:

> UDP is sessionless protocol, working on level of individual packets, but in order to support multiple packets exchange, gobetween associates elected backend with client address. This association ("session") is dropped if client_idle_timeout or backend_idle_timeout is overdue, or if there were more than max_responses responses from backend, or more than max_requests from the client.
> 
> (since 0.6.0) If neither client_idle_timeout nor backend_idle_timeout are specified, and no max_requests and max_responses as well, UDP 'sessions' will be tracked forever and gobetween memory footprint will grow. Starting from version 0.6.0 gobetween forbids such configuration and requires to add timeouts or request/response limits.


So, if you know that your backend and client both actively interact by sending packets, you can set max_responses = 0 and add client_idle_timeout and (or) backend_idle_timeout to your server config:

```
[servers.udpsample]
bind = "0.0.0.0:4000"
protocol = "udp"
balance = "iphash"
client_idle_timeout = "10s"
backend_idle_timeout = "10s"

  [servers.udpsample.udp]
  max_requests  =  0
  max_responses = 0

  [servers.udpsample.discovery]
  kind = "static"
  static_list = [
      "XX:1194",
      "XX:1194",
      "XX:1194"
  ]
```
