### ISSUE TITLE
ACL Consul Tokens

### ISSUE THREAD

**Issue by vankosa** [yyyar/gobetween#195]
The possibility of using tokens is required when the consul uses ACL mechanisms, otherwise service discovery does not work by means of consul

In general, an option is needed (for example, consul_token in [servers.default .discovery]), which will be processed by api in the form http://localhost:8500/v1/agent/services?token=123, where 123 is the required token, which has access to the described services

**Comment by illarion** [comment]
@vankosa could you please check if it works for you?

**Comment by yyyar** [comment]
Merged to master
