### ISSUE TITLE
Unable to launch gobetween docker container with error "not a directory"

### ISSUE THREAD

**Issue by vishal-yadav** [yyyar/gobetween#196]
Though [steps](http://gobetween.io/documentation.html#docker) for running gobetween container is straight forward, encountered below issue. Not sure if I am missing something!

```
 $ ls `pwd`/config/gobetween.toml
 /home/vishalcdac/workspace/gobetween/config/gobetween.toml
 
 $ docker run -p 80:80 -v `pwd`/config/gobetween.toml:/etc/gobetween/conf/:rw yyyar/gobetween
 2019/01/21 05:45:37 gobetween v0.6.1
 2019/01/21 05:45:37 open /etc/gobetween/conf/gobetween.toml: not a directory

```

**Comment by vishal-yadav** [comment]
Okay so looks like need to change the docker steps/instruction from:
`$ docker run -p 80:80 -v /path/to/conf/gobetween.toml:/etc/gobetween/conf/:rw yyyar/gobetween`
to:
`docker run -p 80:80 -v /path/to/conf:/etc/gobetween/conf:rw yyyar/gobetween`

as directory is (volume) mounted, not file.

**Comment by illarion** [comment]
@vishal-yadav thank you. I've just updated the wiki
