### ISSUE TITLE
Windows exec discovery failed 

### ISSUE THREAD

**Issue by nickdoikov** [yyyar/gobetween#2]
exec discovery script :

        @ECHO OFF
        echo webseerver1.loc:80 weight=1
        echo(
        echo webserver2.loc:80 weight=1

discovery config section :

        [servers.sample.discovery]  
        kind = "exec"
        exec_command = ['D:\scripts\exec_discovery.bat'] 
        exec_command = ['node', 'D:\scripts\test.js'] 

Gobetween can discovery only last server from discovery script because of a newline character difference between windows and linux.

Need to make discovery regexp for exec discovery configurable.

**Comment by kikom** [comment]
Done
