### ISSUE TITLE
Add support for environment variables in the config

### ISSUE THREAD

**Issue by pritstift** [yyyar/gobetween#201]
For containerizing gobetween, it would be useful to be able to use placeholders, or environment variables in the configuration file, e.g. like this:

`srv_lookup_server = "${SOME_ENV}"`

**Comment by cunningwasabi** [comment]
For me, it would be useful to be able to say;
./gobetween --config blah.toml --var 'srv_lookup_server = 1.1.1.1'
because I have multiple copies of a config file with different srv_lookup_server settings.

**Comment by yyyar** [comment]
Added possibility to use env vars substitution in config files. By default it's turned off.
To enable this functionality gobetween should be run with '-e' or '--use-config-env-vars':

Example:
`BIND=0.0.0.0:1234 gobetween -e -c "/path/to/config.toml"`

In this case all `${BIND}` placeholders within config would be replaced with `0.0.0.0:1234`.

**Comment by yyyar** [comment]
@nuttysquirrel you can now do the same with env vars, i.e.:

in config:
```
....
   srv_lookup_server = "${SRV_LOOKUP_SERVER}"
....
```

and then 
```
SRV_LOOKUP_SERVER=1.1.1.1 ./gobetween --use-config-env-vars --config blah.toml
```
Would it work for you?

We'll merge this feature in develop shortly and then it would be available in next release.

**Comment by pritstift** [comment]
Awesome!

**Comment by yyyar** [comment]
Also, added doc to wiki page: https://github.com/yyyar/gobetween/wiki/Configuration#using-env-vars-substitution-in-config-file
