### ISSUE TITLE
discovery and the use of "priority"

### ISSUE THREAD

**Issue by nuttysquirrel** [yyyar/gobetween#204]
I'm using gobetween as a front end for an anycast dns setup.
I wanted to be able to say "use 1.1.1.1 always, unless healthcheck marks it down - then use 2.2.2.2"
Current setup runs a dynamic discovery every 10 minutes, with a healthcheck every minute.... 
Reading the documentation on github a number of times didn't make it clear to me how to do the 'absolute priority' situation I described, so I guessed maybe returning 'priority' in discovery...
So, the discovery mechanism returns;
1.1.1.1 priority=1
2.2.2.2 priorty=2
However, gobetween seems to ignore the priority and uses both of them.
sorry if this is obviousky crazy - 'go' is new to me and i'm still going through the source to try and understand it.

**Comment by cunningwasabi** [comment]
Added new balance mechanism "priority". #205

**Comment by cunningwasabi** [comment]
#205 replaced by #211

**Comment by yyyar** [comment]
Merged to master, will be available in next release.
