### ISSUE TITLE
LetsEncrypt not working - still looking for certs

### ISSUE THREAD

**Issue by mrbarletta** [yyyar/gobetween#214]
Thanks for this piece of work!

Version 0.6 and 0.6.1  fails with error `[FATAL] (manager): open : no such file or directory` 

For what I could see its still trying to load the certs even where acme_hosts is set and no certs are defined. (tried also defining the certs as an empty string)
 
Any ideas?  

This is the config I used
```
[logging]
level = "debug"   # "debug" | "info" | "warn" | "error"
output = "stdout" # "stdout" | "stderr" | "/path/to/gobetween.log"

[api]
enabled = false  # true | false
bind = "0.0.0.0:8080"  # "host:port"
cors = false    # cross-origin resource sharing

[defaults]
max_connections = 0              # Maximum simultaneous connections to the server
client_idle_timeout = "0"        # Client inactivity duration before forced connection drop
backend_idle_timeout = "0"       # Backend inactivity duration before forced connection drop
backend_connection_timeout = "0" # Backend connection timeout (ignored in udp)

[acme]                           # (optional)
challenge = "http"               # (optional) http | sni | dns
http_bind = "0.0.0.0:80"         # (optional) It is possible to bind to other port, but letsencrypt will send requests to http(80) anyway
cache_dir = "/tmp"               # (optional) directory to put acme certificates

[servers]

[servers.sample_443]
protocol = "tls"
bind = "0.0.0.0:443"

  [servers.sample_443.discovery]
  kind = "static"
  static_list = [
      "127.0.0.1:3333"
  ]

  [servers.sample_443.tls]             # (required) if protocol == "tls"
  acme_hosts = [
  "mrb.lionix.me"
  ]
```

**Comment by illarion** [comment]
Hello @mrbarletta !

Please check following
1. Do you own mrb.lionix.me domain?
2. Does A record of mrb.lionix.me point to the server that is running gobetween?
3. Is port 80 (http) accessible and open on firewall?
4. Does gobetween has access to /tmp and the folder exists?
5. Do you have full log?

**Comment by mrbarletta** [comment]
Thanks @illarion  for your prompt reply.

1. Yes 
2. Yes, both a A record and a AAAA one.
3. no firewall present.
4. currently running gobetween with root access
5. this is the only thing stdout is showing in debug mode
```
gobetween v0.6.1
2019-04-09 00:04:11 [INFO ] (manager): Initializing...
2019-04-09 00:04:11 [INFO ] (services): Creating acme
2019-04-09 00:04:11 [FATAL] (manager): open : no such file or directory
```

I commented on the code in the file `server/tcp/server.go` so it will not try to load the SSL files and it works (but of course no SSL support is loaded)
```
	server.tlsConfig, err = tlsutil.MakeTlsConfig(cfg.Tls, server.GetCertificate)
	if err != nil {
		return nil, err
	}

```

Any Idea how I might troubleshoot this?

**Comment by mrbarletta** [comment]
thanks @illarion  it works now!  I wish I had figured out that myself sorry to bother you guys.

awesome work! 

ps: i don't close the ticket so you can merge and close on merge-to-master
