### ISSUE TITLE
panic: runtime error when removing UDP server

### ISSUE THREAD

**Issue by waaayfar3r** [yyyar/gobetween#215]
Steps to reproduce:
- launch with a UDP server in config
- remove the server via API

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd1772d]

goroutine 14 [running]:
github.com/yyyar/gobetween/server/udp.(*Server).serve.func1(0xc00032e000, 0x0, 0x1, 0x0, 0x0)
        /home/yyyar/workspace/gobetween/server/udp/server.go:194 +0x2cd
created by github.com/yyyar/gobetween/server/udp.(*Server).serve
        /home/yyyar/workspace/gobetween/server/udp/server.go:187 +0xc6
```

Server options:
```
  [servers.testdns]
    max_connections = 0
    client_idle_timeout = "0"
    backend_idle_timeout = "0"
    backend_connection_timeout = "0"
    bind = "0.0.0.0:5353"
    protocol = "udp"
    balance = "roundrobin"
    [servers.testdns.udp]
      max_requests = 0
      max_responses = 1
    [servers.testdns.discovery]
      kind = "static"
      failpolicy = "keeplast"
      interval = "0"
      timeout = "0"
      static_list = ["8.8.8.8:53"]
    [servers.testdns.access]
      default = "deny"
      rules = ["allow 0.0.0.0/0"]
    [servers.testdns.healthcheck]
      kind = "none"
      interval = "0"
      passes = 1
      fails = 1
      timeout = "0"
```

**Comment by waaayfar3r** [comment]
This only happens when there are access rules defined (doesn't matter which ones though). The error is related to this line (_server.go:194_):
`if !this.access.Allows(&clientAddr.IP) {`

It is unclear though why the error only happens on server removal (everything works fine until then).

**Comment by waaayfar3r** [comment]
My research has shown that this issue is caused by goroutine inside `serve` function trying to access `serverConn` after it has been stopped from `Start` function (_server.go:136_: `this.serverConn.Close()`).
Apparent reason for this is goroutine inside `serve` checking `this.stop` variable _**after**_ referencing `serverConn` which is deleted in this case. Going to create pull request anytime soon.

**Comment by illarion** [comment]
@waaayfar3r thank you for research! Waiting for PR
