### ISSUE TITLE
Does/can GoBetween load balance LXD containers

### ISSUE THREAD

**Issue by bmullan** [yyyar/gobetween#217]
I saw where it states it has a the ability to query a Backend for LXD.

From looking at **config/gobetween.toml** I can see that it looks like you can configure both local and remote LXD servers.

Does GoBetween support both the apt-get LXD and the SNAP LXD ?

thanks for any answer
Brian

**Comment by illarion** [comment]
Adding @jtopjian to a discussion

**Comment by illarion** [comment]
@bmullan please refer to documentation https://github.com/yyyar/gobetween/wiki/Discovery#lxd

**Comment by jtopjian** [comment]
> Does GoBetween support both the apt-get LXD and the SNAP LXD ?

Yes

If you are communicating to LXD via https, then both will work with no configuration changes at all.

If you are communicating via socket and you installed LXD via snap, you can do one of two things:

1. Make sure you run the `lxd.migrate` script or
2. Update the socket path in the gobetween config `lxd_server_address`.

**Comment by illarion** [comment]
@jtopjian thank you for good explanation! @bmullan hope this solves your question.

Thank you!

**Comment by illarion** [comment]
Updated documentation: https://github.com/yyyar/gobetween/wiki/Discovery#notes
