### ISSUE TITLE
Dynamic backend resolve during query

### ISSUE THREAD

**Issue by AtzeDeVries** [yyyar/gobetween#221]
Hi,

Were are trying to route traffic through a single ip and route it to different ip:port in the backend. The traffic is layer 7, but not http... 
We can route the traffic using SNI and this works fine with GB. The list of different backends we support is large (about 400) so it would be nice if the resolve to backend wold be dynamic. 

This could be done by quering dns (using CoreDNS with ipin plugin) when a request is made. Or use the sni name to rewrite it to an ip. For example 172-16-33-10-8080.example.org should be routed to 172.16.33.10:8080. Do you think this is possible with GB?

(ow and please note that TLS should also be offloaded).

**Comment by nickdoikov** [comment]
Hello @AtzeDeVries  you can use exec discovery for discovery needs:
https://github.com/yyyar/gobetween/wiki/Discovery#exec

**Comment by AtzeDeVries** [comment]
Thnx for the reply. 

The exec is run at startup, so you still need a list of all sni's. If GB could generate a backend based on the sni it would be great. In our case the list is not that easy to get and it is updated often.
I agree that using dns would we to slow.

**Comment by nickdoikov** [comment]
@AtzeDeVries seems like you are not catch the idea of discovery
you can define failpolicy (what to do if backend discovery timed out ), backend discovery intervals  ,  discovery timeout .
please read wiki and config to more details.  

```
kind = "<kind>"         # (required)
failpolicy = "keeplast" # (optional) "keeplast" | "setempty" - what to do with backends if discovery fails
interval = "0s"         # (required) backends cache invalidation interval; 0 means never.
timeout = "5s"          # (optional) max time to wait for discover until falling to failpolicy
```


So ,in general i did not see any advantage to implement dynamic discovery that  can cause memory overhaul by design due a tcp nature.

**Comment by AtzeDeVries** [comment]
Ah ok, i missed that part. This can help us in a alternative solution. 
We want to have a vpn like solution where in our cloud we can connect a set of ip's in our datacenter but we can't have the routes in our cloud. So if would be nice if a LB automatically resoolved 172-16-30-12-8000 to 172.16.30.12:8000 using SNI and TLS offloading.

**Comment by nickdoikov** [comment]
i'm insisting on future problems due a data cache and possibility of failures due a dynamic dns backend resolve. it can  also be easily to transform into the attack

**Comment by AtzeDeVries** [comment]
ok thnx. So let's close this ticket since the topic has been discussed i think.
