### ISSUE TITLE
Buildin for Windows

### ISSUE THREAD

**Issue by usernametaken** [yyyar/gobetween#223]
I tried to build for Windows AMD64

1) I tried building on Windows for Windows 
2) I tried to build on Linux for Windows

On both platforms I get the same issue :-(

../pkg/mod/github.com/eric-lindau/udpfacade@v0.0.0-20190425230512-031998cc71fa/udp.go:29:47: **undefined: syscall.IPPROTO_RAW**
../pkg/mod/github.com/eric-lindau/udpfacade@v0.0.0-20190425230512-031998cc71fa/udp.go:38:37: ****cannot use int(fd) (type int) as type syscall.Handle in argument to syscall.SetsockoptInt****
../pkg/mod/github.com/eric-lindau/udpfacade@v0.0.0-20190425230512-031998cc71fa/udp.go:38:63: **undefined: syscall.IP_HDRINCL**

I know it must be possible because I downloaded the windows binary and that works fine... :-)

**Comment by yyyar** [comment]
Seems cross-compiling for windows does not work anymore since #218 and we missed it.
@eric-lindau maybe you have any thoughts how to fix it?
Thanks!

**Comment by eric-lindau** [comment]
The only thing I can think of for now is having some sort of default implementation/warning for platforms that aren't Linux/Darwin/etc in my package and documenting this restriction for the UDP forwarding feature.

Until I/someone does some work on implementing this for Windows/other platforms there is no easy fix since this relies on POSIX syscalls, so I think this might be necessary.

What do you think?

**Comment by yyyar** [comment]
@eric-lindau maybe until someone implement this for Windows, you could add conditional compilation within udpfacade library, and provide mock blank implementation for Windows that will return 'Not implemented on this platform' error for all public functions. In this case gobetween will compile for all platforms, but transparent udp would work only for linux.

@illarion @nickdoikov what do you think?

**Comment by yyyar** [comment]
We can't release 0.8.0 without Windows support since obviously there are users who use it on Windows. So either we need to solve it somehow until 0.8.0, or remove this functionality (what i wouldn't want to do since it's a great feature to have).

**Comment by nickdoikov** [comment]
@yyyar @illarion  @eric-lindau 
 It is very bad idea to split functionality between different OS  builds.
there are two options:
1) find  workaround to make this function workable under all OS
2) mock it on library level and add errors  to allow code successfully build under all OS and throw errors if unsupported option used under Windows.

if there are no way to do one  of this options it will be better to exclude this functionality from code completely.

**Comment by eric-lindau** [comment]
Right - I believe the best way for now is the second option, as I haven't done any research of raw sockets on Windows (or whatever the equivalent might be). That is, unless someone comes around with this experience, but this could be a temporary solution.

**Comment by nickdoikov** [comment]
@eric-lindau , so if the mid-term solution was defined could you please proceed with this fix?

**Comment by yyyar** [comment]
Thanks, @eric-lindau 
After merging #225, it compiles for windows and when using transparent=true for udp shows:

```
2019-06-21 13:34:00 [INFO ] (manager): Initializing...
2019-06-21 13:34:00 [INFO ] (api): Starting up API
2019-06-21 13:34:00 [INFO ] (server): Creating 'sample': 0.0.0.0:3000 weight static none
2019-06-21 13:34:00 [INFO ] (scheduler): Starting scheduler sample
2019-06-21 13:34:00 [INFO ] (api): Starting HTTP server :8888
2019-06-21 13:34:00 [INFO ] (metrics): Metrics disabled
2019-06-21 13:34:00 [INFO ] (udp/server): Creating UDP server 'udpsample': localhost:4000 weight static none
2019-06-21 13:34:00 [INFO ] (scheduler): Starting scheduler udpsample
2019-06-21 13:34:00 [INFO ] (manager): Initialized
2019-06-21 13:35:27 [ERROR] (udp/server): Could not elect/connect to backend: Could not dial UDP addr 8.8.8.8:53 from 127.0.0.1:51315: transparent udp connection not implemented for windows
```

So seems good so far.
We'll need update documentation and wiki to mention transparent mode does not work on Windows.

**Comment by yyyar** [comment]
@usernametaken could you please try build on Windows again on current master branch? It should work now after @eric-lindau fix. Thanks!
