### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by arjun1638** [yyyar/gobetween#234]
I am new to go and tried to install on gobetween on ubuntu, but facing issue with the setup, looking for any help or guidance 
-------------------------------------------
go build -v -o ./bin/gobetween -ldflags '-X main.version=0.8.0+snapshot -X main.revision=fef9717144c8300ce0d482a82997f1f607668a18 -X main.branch=master' .
main.go:14:2: cannot find package "github.com/yyyar/gobetween/api" in any of:
	/usr/local/go/src/github.com/yyyar/gobetween/api (from $GOROOT)
	/home/sai/Projects/proj1/src/github.com/yyyar/gobetween/api (from $GOPATH)
main.go:15:2: cannot find package "github.com/yyyar/gobetween/cmd" in any of:
	/usr/local/go/src/github.com/yyyar/gobetween/cmd (from $GOROOT)
	/home/sai/Projects/proj1/src/github.com/yyyar/gobetween/cmd (from $GOPATH)
main.go:16:2: cannot find package "github.com/yyyar/gobetween/config" in any of:
	/usr/local/go/src/github.com/yyyar/gobetween/config (from $GOROOT)
	/home/sai/Projects/proj1/src/github.com/yyyar/gobetween/config (from $GOPATH)
main.go:17:2: cannot find package "github.com/yyyar/gobetween/info" in any of:
	/usr/local/go/src/github.com/yyyar/gobetween/info (from $GOROOT)
	/home/sai/Projects/proj1/src/github.com/yyyar/gobetween/info (from $GOPATH)
main.go:18:2: cannot find package "github.com/yyyar/gobetween/logging" in any of:
	/usr/local/go/src/github.com/yyyar/gobetween/logging (from $GOROOT)
	/home/sai/Projects/proj1/src/github.com/yyyar/gobetween/logging (from $GOPATH)
main.go:19:2: cannot find package "github.com/yyyar/gobetween/manager" in any of:
	/usr/local/go/src/github.com/yyyar/gobetween/manager (from $GOROOT)
	/home/sai/Projects/proj1/src/github.com/yyyar/gobetween/manager (from $GOPATH)
main.go:20:2: cannot find package "github.com/yyyar/gobetween/metrics" in any of:
	/usr/local/go/src/github.com/yyyar/gobetween/metrics (from $GOROOT)
	/home/sai/Projects/proj1/src/github.com/yyyar/gobetween/metrics (from $GOPATH)
main.go:21:2: cannot find package "github.com/yyyar/gobetween/utils/codec" in any of:
	/usr/local/go/src/github.com/yyyar/gobetween/utils/codec (from $GOROOT)
	/home/sai/Projects/proj1/src/github.com/yyyar/gobetween/utils/codec (from $GOPATH)
Makefile:31: recipe for target 'build' failed
make: *** [build] Error 1

----------------------------------------
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sai/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sai/Projects/proj1"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/sai/Projects/proj1/gobetween/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build416574766=/tmp/go-build -gno-record-gcc-switches"

**Comment by shantanugadgil** [comment]
Do you really want to build gobetween from source or do you want to use gobetween?

You can grab the binary from:
https://github.com/yyyar/gobetween/releases

**Comment by arjun1638** [comment]
Thanks for reverting, it helped me. I have created docker-compose with 3 apache server for testing.
