### ISSUE TITLE
Client IP

### ISSUE THREAD

**Issue by dewanshamsul** [yyyar/gobetween#242]
Hi,

We use gobetween to load balance http and https request to our servers.
Please check the following diagram.

Client>>>>>>>>>>>>>>>>Server>>>>>>>API>>>>>>>>>Remote

So when a client talks to our server and make an API call to the remote server, the remote server sees that the request is coming from Client's IP address.

But when we use gobetween the remote server sees that the requests are coming from Server's IP address. 

We need to use gobetween and make the remote server see that the requests are actually coming from Client's IP instead of the server's IP.

Gobetween config looks like the following.
Note: I changed the public IP to private IP.

`[servers.sample]
bind = "0.0.0.0:80"
protocol = "tcp"
balance = "iphash1"

max_connections = 10000
transparent = true
client_idle_timeout = "10m"
backend_idle_timeout = "10m"
backend_connection_timeout = "2s"

    [servers.sample.discovery]
    kind = "static"
    static_list = [
      "192.168.0.104:8080 weight=3",
      "10.0.0.134:8080 weight=1",
    ]

    [servers.sample.healthcheck]
    fails = 1
    passes = 1
    interval = "2s"
    timeout="1s"
    kind = "ping"
    ping_timeout_duration = "500ms"

[servers.https]
bind = "0.0.0.0:443"
protocol = "tcp"
balance = "iphash1"

max_connections = 10000
transparent = true
client_idle_timeout = "10m"
backend_idle_timeout = "10m"
backend_connection_timeout = "2s"

    [servers.https.discovery]
    kind = "static"
    static_list = [
      "192.168.0.104:8443 weight=3",
      "10.0.0.134:8443 weight=1",
    ]

    [servers.https.healthcheck]
    fails = 1
    passes = 1
    interval = "2s"
    timeout="1s"
    kind = "ping"
    ping_timeout_duration = "500ms"
`

**Comment by nickdoikov** [comment]
hi, it is not implemented because usually lb and default gateway sit on the different ip's and it is impossible to do such requested configuration on l4 in this case.
you need something like nginx or haproxy to set http header that will contain source ip and protocol in case if you need it also.

**Comment by dewanshamsul** [comment]
Thank you for your reply.
We would love to see gobetween working in layer7.
For now I am moving to haproxy.
