### ISSUE TITLE
Traffic Rx and TX is always zero

### ISSUE THREAD

**Issue by praveenkumar2608** [yyyar/gobetween#245]
Hi,

I am using gobetween and when I query the traffic stats using APP Get /servers/server1, the traffic rx and tx (Bytes and bps) is always zero.

**Comment by yyyar** [comment]
Hi @praveenkumar2608 
Please provide your config file and full GET /servers/server1 response body so we could check if something goes wrong. Thanks.

**Comment by praveenkumar2608** [comment]
Hi, 

Actually it was config mistake, I sorted out the problem. I can see the data as expected. Is there a way to load balance or reverse proxy the UDP protocol random ports.

**Comment by yyyar** [comment]
Not sure what you exactly mean under proxy UDP random ports.
Please refer to the UDP doc https://github.com/yyyar/gobetween/wiki/Protocols#udp
If it does not do what you need please create separate issue and describe your use case.

Closing this one since it sorted out.
