### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference when no default section in config

### ISSUE THREAD

**Issue by rnagarajan12** [yyyar/gobetween#27]
./gobetween
2016-07-25 09:05:32 [INFO ] (main): gobetween v0.2.0
2016-07-25 09:05:32 [INFO ] (main): Using config file ./gobetween.toml
2016-07-25 09:05:32 [INFO ] (manager): Initializing...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x464d22]

goroutine 6 [running]:
panic(0xa3ca00, 0xc82000a100)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
_/home/yyyar/workspace/gobetween/src/manager.prepareConfig(0xc8201ce184, 0x6, 0xc8201cd530, 0xc8201cd540, 0xc8201cdb90, 0xc8201cdb70, 0xc8201cc7c0, 0xc, 0xc8201cc838, 0x3, ...)
	/home/yyyar/workspace/gobetween/src/manager/manager.go:269 +0x8b2
_/home/yyyar/workspace/gobetween/src/manager.Create(0xc8201ce184, 0x6, 0xc8201cd530, 0xc8201cd540, 0xc8201cdb90, 0xc8201cdb70, 0xc8201cc7c0, 0xc, 0xc8201cc838, 0x3, ...)
	/home/yyyar/workspace/gobetween/src/manager/manager.go:116 +0xd7
_/home/yyyar/workspace/gobetween/src/manager.Initialize(0xc8201cc258, 0x5, 0xc8201cc320, 0x6, 0x1, 0xc8201cc4c0, 0x5, 0xc8201d2160, 0x0, 0x0, ...)
	/home/yyyar/workspace/gobetween/src/manager/manager.go:46 +0x27b
created by main.main
	/home/yyyar/workspace/gobetween/src/main.go:83 +0x4f3

I downloaded the binary package gobetween_0.2.0_linux_amd64.tar 

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

uname -a
Linux 3.19.0-61-generic #69~14.04.1-Ubuntu SMP Thu Jun 9 09:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nickdoikov** [comment]
hello , consul support aviliable only in 0.3 release.
If you want toy test it now - please download latest container : docker pull yyar/gobelween:latest
or build it manually from feat-#7-consul-discovery

**Comment by rnagarajan12** [comment]
I am not using cosul..
This is my toml config, I tried wiht 0.1.0 version, all worked. but not with 0.20=.0
#
# Contains logging configuration
#
[logging]

level = "debug"    # "debug" | "info" | "warn" | "error"
output = "stdout" # "stdout" | "stderr" | "/path/to/gobetween.log"

#[api]
#enabled = true  # true | false
#bind = ":8888"  # "host:port"
#  [api.basic_auth]   # (optional) Enable HTTP Basic Auth
#  login = "admin"    # HTTP Auth Login
#  password = "1111"  # HTTP Auth Password

[servers.sample]
bind = "0.0.0.0:3000"
protocol = "tcp"
balance = "weight"

max_connections = 10
client_idle_timeout = "5s"
backend_idle_timeout = "5s"
backend_connection_timeout = "2s"

  [servers.sample.healthcheck]
  kind = "ping"
  interval = "5s"
  timeout = "500ms"
  fails = 3
  passes = 3

  [servers.sample.discovery]
  #kind = "static"
  #static_list = [
  #  "localhost:8000 weight=1",
  #  "localhost:8001 weight=2"
  #]
  kind = "exec"
  exec_command = ["/usr/local/sbin/test.sh"]

**Comment by nickdoikov** [comment]
thank you for ticket . we will fix it in 0.3 release .
for now [defaults] section is required



add this sectionto  the top of config file  and it will fix issue .

`
[defaults]
max_connections = 0
client_idle_timeout = "0"
backend_idle_timeout = "0"
backend_connection_timeout = "0"

`

**Comment by rnagarajan12** [comment]
That's fixed. thanks for the quick help..

Just an another wish,

Can you guys also send original source IP to container logs?
For ex, I request proxy from 
10..0.0.0, and my container logs , I get docker default gateway,? Is it possible, I can also see the original request IP in the logs?

(server.handle): Begin 10.0.0.0: -> [::]:3000 -> container_ip:443

172.17.65.1 - -  "GET / HTTP/1.1" 200 9819 "https://hostname:3000" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36

**Comment by nickdoikov** [comment]
please provide more details and create separate ticket with feature request
