### ISSUE TITLE
gobetween is not redirecting my request to my servers

### ISSUE THREAD

**Issue by antoniogamiz** [yyyar/gobetween#275]
Hi, I am trying to use `gobetween` as load bolancer. I have two different web servers (using Apache), with the following IP addresses: `192.168.56.102`, `192.168.56.103`. I have installed `gobetween` in another machine (in reality, all servers are virtual machines with Ubuntu 18.04 running in the same computer) with the following configuration:

    [servers]
    
    # http 
    [servers.sample] 
    protocol = "tcp" 
    bind = "localhost:3000" 
    balance = "roundrobin"
    
    max_connections = 10000 
    client_idle_timeout = "10m" 
    backend_idle_timeout = "10m" 
    backend_connection_timeout = "2s"
    
      [servers.sample.discovery]   
      kind = "static"   
      static_list = [
          "192.168.56.102:80",
          "192.168.56.103:80"   
      ]

But when I make a request with `curl http://192.168.56.104:3000/` I do not get the home page of my web servers. ¿Any idea where's the problem?

**Comment by yyyar** [comment]
@antoniogamiz 
Could you please provide gobetween log output?

Also try to use bind = "0.0.0.0:3000" because you now binding to localhost, but trying to access it via IP address.

**Comment by antoniogamiz** [comment]
Oh, you were right, the problem was `localhost`. Thanks a lot for the help :).
