### ISSUE TITLE
Expose servers stats

### ISSUE THREAD

**Issue by nickdoikov** [yyyar/gobetween#3]
server:
  - active connections
  - total connections
  - traffic rx/tx (total)
  - current traffic rx/tx (gb,mb,kb,b,/s)
  - backends
      - status : live | down
      - inbound traffic (total/avg(1 sec))
      - outbound traffic (total/avg(1 sec))
      - active connections
      - total connections

**Comment by nickdoikov** [comment]
everything works as expected.

**Comment by yyyar** [comment]
Done
