### ISSUE TITLE
HTTP to HTTPS redirection

### ISSUE THREAD

**Issue by skakee** [yyyar/gobetween#300]
Can gobetween be setup to reply to all HTTP requests with a redirect to HTTPS of the same URL?

**Comment by jpic** [comment]
That wouldn't be a very secure way to enforce HTTPS: vulnerable to MITM.

**Comment by skakee** [comment]
jpic, there might be a misunderstanding here.  Redirecting HTTP requests to HTTPS is standard operating procedure (see http://google.com for example).  What do you do when someone tries to access your site using HTTP?

**Comment by illarion** [comment]
Sorry, gobetween is not an http proxy, it works on sockets (l4) layer. What can it do for you is to serve secure connections (any tls protocol including https) for an unsecured backend (e.g. http).
