### ISSUE TITLE
Project dead and no maintainers?

### ISSUE THREAD

**Issue by leolux** [yyyar/gobetween#312]
The projects current status should be "Under active development. Currently in use in several highly loaded production environments.". But the last commit has been 8 months ago and there are issues without responses.

Any idea why the project has been stopped?

**Comment by leolux** [comment]
@yyyar, @nickdoikov, @kikom, @illarion What is the current state of this project and who are the current maintainers?

**Comment by illarion** [comment]
Currently, the project is in maintenance mode, due to a lack of time. If you have specific changes in mind, please make PR

**Comment by leolux** [comment]
Alright, thank you for clearification
