### ISSUE TITLE
Add go get into Makefile

### ISSUE THREAD

**Issue by SergeyOvsienko** [yyyar/gobetween#51]
Hi ALL

For build gobeetwen at the clear system add this lines into Makefile

go get github.com/BurntSushi/toml
go get github.com/Sirupsen/logrus
go get github.com/elgs/gojq
go get github.com/fsouza/go-dockerclient
go get github.com/gin-gonic/gin
go get github.com/hashicorp/consul/api
go get github.com/miekg/dns
go get github.com/spf13/cobra

**Comment by yyyar** [comment]
@SergeyOvsienko It's already there, just run:
$ make deps

**Comment by SergeyOvsienko** [comment]
Провтыкал, мудак, прсотите)
