### ISSUE TITLE
SNI support for proxying

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#53]
Hi,
Is there a plan in the near future to implement SNI based routing?

Regards,
Shantanu

BTW:
Awesome software which I discovered only by accident!!!
The Consul discovery backend is truly great!!!
 👍 👍

**Comment by nickdoikov** [comment]
hello @shantanugadgil  ,  SNI based routing?  maybe we wll think about that.
could you please describe real life usecase ?
you want to  terminate ssl with multiple certs on one port?

**Comment by shantanugadgil** [comment]
Hi @nickdoikov  thanks for your quick reply.

I do not want to terminate SSL.

My use case is like this:
A single **gobetween** endpoint will be hit by various different "requesting" entities on the same incoming port (443).
Based on the SNI field, the traffic will get redirected to the appropriate backend.
(The backend would come from the Consul discovery)

What I am thinking is something like the following: (without the sticky bits)
http://blog.haproxy.com/2012/04/13/enhanced-ssl-load-balancing-with-server-name-indication-sni-tls-extension/

**Comment by nickdoikov** [comment]
ok , i see . I have read same article  you  mentoined  :)

we will think about that  and look at possibility to implement this.

**Comment by shantanugadgil** [comment]
Hi,
wrt to the TCP SNI, I stumbled upon this:
https://github.com/eBay/fabio/wiki/Features#13-%EF%B8%8F-new-feature-1

Thought it might be helpful!

Regards,
Shantanu

**Comment by illarion** [comment]
@shantanugadgil please take a view at the example of config section. In the end of the day I am planning to finalize the branch and you'll be able to build and test it

```
[servers.default.sni]                    # (optional)
enabled = false                          # (required) if true server will lookup sni from ClientHello
matching = "exact"                       # (optional) "exact" | "regexp" if regexp, then compile sni tag of backend as regexp.
read_timeout = "2s"                      # (optional) timeout for reading sni from client
unexpected_hostname_strategy = "default" # (optional) "default" | "reject" | "any" strategy for dealing with unknown hostname requests
                                         #    "default" -- forward connections to backends with no sni tag
                                         #    "reject" -- drop connection
                                         #    "any" -- forward to any available backend

```

**Comment by shantanugadgil** [comment]
Hi,
I am a bit busy for a few days. I have done some initial setup. Once I get my multiple backends running I'll try to do a complete test.

**Comment by yyyar** [comment]
merged to master

**Comment by illarion** [comment]
@shantanugadgil https://github.com/yyyar/gobetween/wiki/Server-Name-Indication

**Comment by shantanugadgil** [comment]
Hi @illarion @yyyar 
Sorry about the delay, but I had been busy with a few other things.
Over the past few days, I have been able to successfully test this and things are looking good.
* Creating the backend "SSL enabled" server dockers is what took some time.

I'll try to capture my test setups as pictures; this can give more ideas to folks who may need this functionality.

Thanks and Regards,
Shantanu

**Comment by shantanugadgil** [comment]
Hi,

The new changes are working as expected (after some deeper understanding).

My configurations are as follows, I use Nomad and Consul for the co-ordination and job launch.


Setup 1:
![gobetween1](https://cloud.githubusercontent.com/assets/2508915/24521691/a728e150-15aa-11e7-964b-ac02ecccdc7c.png)

Setup 2:

![gobetween2](https://cloud.githubusercontent.com/assets/2508915/24521698/b6890080-15aa-11e7-9b50-bbd48102cad6.png)


Thanks and Regards,
Shantanu
