### ISSUE TITLE
[feature request] gobetween register itself in Consul

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#54]
Hi,
Would it be possible to add a feature where gobetween can register itself in the Consul it would
use for service discovery.
This would helpful when the IP of the Load Balancer may change across reboots.

As of now I am making do with a hackish workaround ...
_A consul agent on the load balancer machine. and a cron job which get the IP of eth0 and recreates
a service definition in '/etc/consul/'._

Regards,
Shantanu

**Comment by nickdoikov** [comment]
it is easy to do with  simple bash script in cron. 
We do not see any benefits to add this functionality directly in GoBetween.

**Comment by shantanugadgil** [comment]
As I said, I am making do with a workaround.

Though, I think there is benefit, when there can be staggered proxies and number of **gobetween** instances can dynamically change for load balancing among themselves behind a static load balancer (say, ELB)

Regards,
Shantanu

**Comment by nickdoikov** [comment]
Shantanu,  it is hard to understand how to implement it properly because you can have multiple interfaces, multiple servers (that should be registered under different service names in Consul).
So in general it needs to propagate proper ip , and multiple servers. 
What servers needs to be registered etc...

Can you describe what you think about it .

**Comment by shantanugadgil** [comment]
Hi, I can explain my requirement, maybe that can help make things a bit clearer.

(The following is an idea, I am still experimenting ...)

Scenario 1:
-----------
I need to have a single load balancer for all my services (when gobetween gets SNI support) and I need to figure out remotely where my gobetween is running. (The machine where gobetween is running could change its IP; my consul servers shall be assumed to be always accessible via DNS/IP)

Scenario 2:
-----------
Until gobetween get SNI support, I shall run multiple instances of gobetween; gobA, gobB and gobC
behind an HAProxy.  _HAProxy is only used for the SNI based routing._

Each gobetween is for a different type of service.
The gobetween servers for each of the service (A,B or C) could scale-up/scale-down in number.
_(This won't happen often, and if it does, I shall use HAProxy+Consul Template to regenerate
the HAProxy config on the main HAProxy)_ 

Hope this helps to clarify what I am experimenting with.
BTW, in my above experiment, the services A, B and C are all docker containers in a Nomad+Consul environment.

🥇

**Comment by illarion** [comment]
@shantanugadgil Ok, let's assume we have SNI support and gobetween can register itself in consul. How will it obtain it's changed external ip in order to register itself?

**Comment by shantanugadgil** [comment]
For a flat network, this could be based on the configured IP address of a specified device.
(possibly we can also specify which network device to use in the config file)

* For typical cloud deployments, where the VMs are NATed, this may not set the correct IP address.
(though over time gobetween could become more aware of the cloud platform :) :) )

Cheers,
Shantanu

**Comment by nickdoikov** [comment]
guys, do we will think  about server`s consul registration   ?

**Comment by shantanugadgil** [comment]
Hi @illarion @nickdoikov 
I have been using a Gobetween Docker image for all my experiments now. (a few months)
I also use Nomad to launch the Docker and register it in Consul.
So, the question of "Where (IP:PORT) is my LoadBalancer running?" is now answered.

Please feel free to close this issue if not required anymore.

Thanks! 👍
