### ISSUE TITLE
pattern matching in the SNI fields

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#57]
Related to #53, would it be possible implement some sort of pattern matching in the SNI field?

Especially useful would:
* doing a case-insensitive match of the SNI field. (clients could send mixed case domain names)
* having a "begins with" type of match.

Basically things which HAProxy supports :grin: 

Ref: https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#7.1.3
>   - prefix match    (-m beg) : the patterns are compared with the beginning of
>     the extracted string, and the ACL matches if any of them matches.

This is not a blocker for me, because for my use case I can "make do" with full matches.
_(I will be using Nomad to launch jobs, and can use Nomad's templating support)_

Regards,
Shantanu

BTW,
I keep checking up on the feat-sni branch, awesome enhancement! :+1:

**Comment by illarion** [comment]
Could you please describe your full use case for both #53 and #57 ?

**Comment by shantanugadgil** [comment]
Hi,

The requirement is pretty much as mentioned in the HAProxy article from 2012 in #53.

For #57, all I was saying was, that an enhancement which would be super-useful would be, if I was able to specify the matching conditions as not only "exact matches" but also some extra conditions on the string being matched (example "begins with", "ends with", etc.)

After thinking about this a bit, I think the cleanest enhancement could be if the match condition is a full REGEX (though this may get to be CPU intensive)

I am using the following as reference:
https://github.com/yyyar/gobetween/commit/1e577612960c3bea42a1c395242aeece4ab10d3c#diff-b9927f925fc49bf0c91bf38f026cd6b1R61

The ability to do pattern matches is not an urgent requirement and as an immediate need, I can make do with 'exact matching' rules.

Regards,
Shantanu

**Comment by illarion** [comment]
@shantanugadgil currently I have implementation that supports exact match and "begins with" match using sni=<prefix>* . Later on it could be replaced with regex matching

The only problem left is how to organize config and this subtask should be done by @yyyar

**Comment by shantanugadgil** [comment]
@illarion Thanks for this.
Waiting for the next release!!! :+1:  :grinning:

**Comment by yyyar** [comment]
merged to master

**Comment by shantanugadgil** [comment]
I have checked out master and am testing things!!!  👍
