### ISSUE TITLE
Load balancing using url parameters

### ISSUE THREAD

**Issue by karteek-gamooga** [yyyar/gobetween#63]
Hi,
Is it possible to load balance using a using a url GET parameter using gobetween, something similar to HAProxy url_param.

https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4-balance

Regards,
Karteek.

**Comment by nickdoikov** [comment]
Hello , Karteek

L7 will be implemented later , now we are focused on implementing full L4 features.

**Comment by karteek-gamooga** [comment]
Thanks for the clarification Nick.
