### ISSUE TITLE
[question] New release for the SNI support?

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#66]
Hi,
With respect to #53 do you plan to make a 0.4.0 release and a new Docker Hub image?

For now, I have compiled the latest master and made a Docker image of it for my personal testing.

Thanks and Regards,
Shantanu

**Comment by illarion** [comment]
We are in the process of finishing testing and fixing small issues found

**Comment by shantanugadgil** [comment]
OK. Thanks! 🏆

**Comment by yyyar** [comment]
@shantanugadgil https://github.com/yyyar/gobetween/releases/tag/0.4.0
