### ISSUE TITLE
multiple Consul service names in Consul discovery

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#67]
Hi,
As per my understanding of the new SNI support (and using Consul as the discovery), 
consider the following example:

workload 1:
service name: myservice
tag: "sni=foo.example.com"

When I want to add another type of workload, but use the same gobetween, I have to register the new workload under the same service name
service name: myservice
tag: "sni=bar.example.com"

This becomes a bit confusing as both types of workloads are visualized under the same Consul service name (in the Consul WebUI)
The main intent is to use a single frontend (bind) port in the gobetween config (usually 443)

My question is:
Would it be possible to allow multiple Consul service names to be specified in the "consul_service_name" parameter.
Example:
 **consul_service_name: "a|b|c"**

This will allow users to visualize the services separately in the Consul WebUI

Regards,
Shantanu

**Comment by nickdoikov** [comment]
why don`t just to register service with another service name ?
consul service paradigm is a 1 name per 1 identical service with identical functionality  .

As for me -you trying to use consul strange/wrong  way . 
you can add env variable during container run and define service  and port (see registrator reference)
also - you can write your own registration module using consul api register ant update endpoint.

I do not see any benefit in adding functionality you talking about.

**Comment by shantanugadgil** [comment]
Hi,
I have two different types of workloads. I'll explain with the config I use.
Also I'll mention my use-case.


What I am a bit confused about is:
How would the gobetween configuration have to look to make gobetween use both these backends
and send traffic to the two different backends based ONLY on SNI field?

My use case: (and I wonder if it possible)
* I want gobetween to listen on a single port "443".
* traffic which reaches gobetween using the sni "hello.myserver.org" will go to any container within the backend "hello".
* traffic which reaches gobetween using the sni "world.myserver.org" will go to any container within the backend "world".
* All containers with workload type "hello" will publish their own service name as "hello" in consul.
* All container with workload type "world" will publish their own service name as "world" consul.

My gobetween config looks exactly like:

```
[api]
enabled = true
bind = ":444"

[logging]
level = "debug"
output = "stdout"

[defaults]
protocol = "tcp"
balance = "leastconn"
max_connections = 0
client_idle_timeout = "30s"
backend_idle_timeout = "30s"
backend_connection_timeout = "30s"

[servers]

[servers.helloworld]
protocol = "tcp"
bind = ":443"
sni_enabled = true

[servers.helloworld.discovery]
kind = "consul"
failpolicy = "setempty"
consul_host = "myconsulserver:8500"
consul_service_name = "helloworld"
consul_service_passing_only = true
interval = "3s"
timeout = "2s"

[servers.helloworld.sni]
enabled = true
matching = "exact"
read_timeout = "2s"
unexpected_hostname_strategy = "reject"
```

for testing, my "hello" and "world" workloads are simple HTTPS servers which respond with echo messages; one echos "hello <date>", the other echos "world: <date>".

**Comment by shantanugadgil** [comment]
I am now registering services with different names.
Closing this now!

Thanks! 👍
