### ISSUE TITLE
Cоnsul service discovery intergration

### ISSUE THREAD

**Issue by nickdoikov** [yyyar/gobetween#7]
Need to add consul discovery service integration.

           consul service discovery api calls :
           https://www.consul.io/docs/agent/http/catalog.html#catalog_services

```text
api enteryponint - ip/hostname:port
api service enterypoint -  /v1/catalog/service/[servicename]
```

```json
[{
	"Node": "ip-172-30-2-11",
	"Address": "172.30.2.11",
	"ServiceID": "ip-172-30-2-11:high_panini:8443",
	"ServiceName": "service1",
	"ServiceTags": ["tag1","tag2"],
	"ServiceAddress": "1.1.1.1",
	"ServicePort": 24338,
	"ServiceEnableTagOverride": false,
	"CreateIndex": 5550785,
	"ModifyIndex": 20803436
}, {
	"Node": "ip-172-30-2-12",
	"Address": "172.30.2.12",
	"ServiceID": "ip-172-30-2-12:insane_kirch:8443",
	"ServiceName": "service1",
	"ServiceTags": ["tag1","tag2"],
	"ServiceAddress": "2.2.2.2",
	"ServicePort": 24138,
	"ServiceEnableTagOverride": false,
	"CreateIndex": 5550914,
	"ModifyIndex": 20803449
}, {
	"Node": "ip-172-30-2-13",
	"Address": "172.30.2.13",
	"ServiceID": "ip-172-30-2-13:happy_shockley:8443",
	"ServiceName": "service1",
	"ServiceTags": ["tag1","tag2"],
	"ServiceAddress": "3.3.3.3",
	"ServicePort": 24338,
	"ServiceEnableTagOverride": false,
	"CreateIndex": 5550996,
	"ModifyIndex": 20803432
}]
```
Need to parse json output from consul and get pool of :
	**"ServiceAddress": "ip/hostname"
	"ServicePort": port**
from there.

Configuration options:

**consul_endpoint=”some_host_name_or_ip:port”
consul_service_name=”service_name”
consul_service_tag=”tag” #optional
consul_api_service_endpoint=/v1/catalog/service/[servicename] #optional
consul_api_service_tls_enabled = false                # (optional) enable client tls auth
consul_api_service_tls_cert_path = '/path/to/cert.pem'
consul_api_service_tls_key_path = '/path/to/key.pem'
consul_api_service_tls_cacert_path = '/path/to/cacert.pem'**

**Comment by nickdoikov** [comment]
also please don`t forget about tls security connection to consul api

**Comment by altvnk** [comment]
I can suggest that Consul API library that can greatly simplify obtaining and filtering service list from consul catalog. [Consul API lib](https://github.com/hashicorp/consul/tree/master/api)
In addition this lib provides mechanisms for interaction with Consul KV. If you are planning Consul KV discovery in future this might be helpful as well.

**Comment by nickdoikov** [comment]
thanks .

**Comment by nickdoikov** [comment]
consul implementation spec is finished.

**Comment by yyyar** [comment]
@nickdoikov  please test feat-#7-consul-discovery
