### ISSUE TITLE
Replace 'python -m SimpleHTTPServer' with gowebhello

### ISSUE THREAD

**Issue by udhos** [yyyar/gobetween#70]
Replace 'python -m SimpleHTTPServer' with gowebhello: https://github.com/udhos/gowebhello

    $ go get github.com/udhos/gowebhello
    $ go install github.com/udhos/gowebhello
    $ ~/go/bin/gowebhello :8000 2>/dev/null &
    $ ~/go/bin/gowebhello :8001 2>/dev/null &

**Comment by illarion** [comment]
@udhos sorry for accidental closing your comment. Could you please describe in more details, why python's SimpleHTTPServer should be replaced with gowebhello?

**Comment by shantanugadgil** [comment]
I think @udhos could be hinting at using a lighter-weight single Go binary based HTTP server than python.
Something like https://github.com/hashicorp/http-echo

On the same note, how about: https://github.com/emilevauge/whoamI
(whoamI provides a lot of similar information)

Regards,
Shantanu

**Comment by shantanugadgil** [comment]
@udhos  @illarion 
Do you have any tips for a Go based (single binary) webserver which can do SSL as well?
My current approach is to use a combination of stunnel (https://www.stunnel.org/index.html) mixed with **whoamI** (https://github.com/emilevauge/whoamI)

The use case here is do quickly demonstrate various features/capabilities/etc. of gobetween and not have external dependencies.

Cheers,
Shantanu

**Comment by udhos** [comment]
@shantanugadgil Just pushed some HTTPS support into https://github.com/udhos/gowebhello

**Comment by shantanugadgil** [comment]
I was able to set this up; works awesome.
Though the example shows HTTP and HTTPS together; I wasn't able to start both at the same time.

**Comment by shantanugadgil** [comment]
@udhos  confirming that this works nicely (HTTP+HTTPS) 👍  🥇 

Thanks,
Shantanu

**Comment by shantanugadgil** [comment]
Hi all,

gowebhello pretty much covers all the use cases for a quick demo; TLS (SSL) included.
I think the documentation can easily be replaced to give examples using udhos' gowebhello.

Which brings me to another question ... How/Where can we suggest edits to the documentation?
i.e. pages of the main website and the github Wiki.

Regards,
Shantanu

**Comment by yyyar** [comment]
Done in #137
