### ISSUE TITLE
Let's Encrypt Support

### ISSUE THREAD

**Issue by jpillora** [yyyar/gobetween#71]
Are there plans to support [Let's Encrypt](https://letsencrypt.org/) on the TLS protocol?

I had [plans](https://github.com/jpillora/tcp-gate) to write a Caddy-like server for TCP/TLS with Automatic TLS. To perform renewal, the TLS listener could temporarily serve TCP connections to respond to the ACME HTTP challenge.

**Comment by yyyar** [comment]
Hi @jpillora 
Yes, we were planning to add ACME and Let's Encrypt support in following releases, we just need to think how it integrate it in a most robust way.
 
Thanks for the question, I'll add this issue to the milestones.

**Comment by illarion** [comment]
@jpillora you can test this branch. Configuration is pretty simple:

```
[servers.test]
protocol = "tls"
bind = "0.0.0.0:443"

  [servers.test.tls]
  acme_enabled = true
  acme_hosts = [
    "foo.com",
    "bar.net",
    "etc.io"
  ]
  acme_cache_dir = "/var/run/whatever" # optional, /tmp by default
```

This

**Comment by jpillora** [comment]
Will test today :smile:

**Comment by ashmckenzie** [comment]
oh boy oh boy!!

**Comment by jpillora** [comment]
Currently, `github.com/lxc/lxd` is failing to build. I've built LXD integration before in Go and pulling in the whole `lxc/lxd` package seems to cause many compilation issues - so I ended up using the REST API from Go and vendoring just structs from `github.com/lxc/lxd/shared`.

Ultimately, it would be nice if `go get github.com/yyyar/gobetween` was all that's needed to build this program, though not a priority I guess. I've got some thoughts on this - I'll create another issue about it soon.

```
$ uname -a
Linux my-hostname-2 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ go version
go version go1.9 linux/amd64
$ apt install -y libc6-dev-i386
...
$ make dep && make build
...
github.com/lxc/lxd/shared/logger
github.com/lxc/lxd/shared
# github.com/lxc/lxd/shared
vendor/src/github.com/lxc/lxd/shared/util_linux.go:39:21: fatal error: sys/acl.h: No such file or directory
compilation terminated.
github.com/lxc/lxd/shared/api
github.com/lxc/lxd/shared/cancel
github.com/lxc/lxd/shared/ioprogress
github.com/lxc/lxd/shared/osarch
golang.org/x/crypto/acme
golang.org/x/crypto/acme/autocert
Makefile:60: recipe for target 'deps' failed
make: *** [deps] Error 2
```

**Comment by jtopjian** [comment]
The `acl.h` dependency is something I noticed recently, too. I'll look into if it's required or if the package that requires it can be ignored.

For now, installing `libacl1-dev` should resolve the issue.

**Comment by jpillora** [comment]
Built, and tested, and working 👍  though might be nice to add some logs showing when it's doing the ACME dance.

Using:
```toml
[servers.test]
protocol = "tls"
bind = "0.0.0.0:443"

  [servers.test.tls]
  acme_enabled = true
  acme_hosts = [
    "my.host.name"
  ]
  acme_cache_dir = "/root/acme"

  [servers.test.discovery]
  kind = "static"
  static_list = [
    "localhost:7777"
  ]
````
