### ISSUE TITLE
[feature request] sni ssl termination support

### ISSUE THREAD

**Issue by nickdoikov** [yyyar/gobetween#75]
According to a ssl use cases please implement Sni-based  tls termination .
Choose certificate based on hostname obtained from HOST field of incoming connection request.
Please do not forget about future let`s encrypt support implementation.

**Comment by shantanugadgil** [comment]
Curious: Is this full L7 support? or a special SNI-only termination where the data is still in pass-through mode.

**Comment by illarion** [comment]
@shantanugadgil It is not L7

**Comment by nickdoikov** [comment]
Sni was implemented long time ago ,  so i`m closing this.
