### ISSUE TITLE
Host-based routing

### ISSUE THREAD

**Issue by ikandars** [yyyar/gobetween#78]
How I achieve Host-based routing (just as Apache’s VHost or Nginx’s Server names). Let say, I have two domain name that need to routes to deferent backend. At the same time, it's all run in same port eg: 80. If it posible, can you share the config.

thx

**Comment by nickdoikov** [comment]
hello @ikandars , unfortunately for now we do not support this feature because now Gobetween   is a l4 load balancer. We have plans to start with l7 but a little bit later.

**Comment by illarion** [comment]
@ikandars but, you can have host based routing for TLS/SSL protocol right now, this feature is called SNI, please read details here: https://github.com/yyyar/gobetween/wiki/Server-Name-Indication

**Comment by ikandars** [comment]
thx @nickdoikov @illarion

**Comment by ikandars** [comment]
I've just notice gobetween is layer 4 balancer. I wouldn't ask this question if I know since the first time. Awesome!
