### ISSUE TITLE
what's the differ from traefik & fabiolb in terms of performance, features & easy to use?

### ISSUE THREAD

**Issue by hbakhtiyor** [yyyar/gobetween#82]

**Comment by shantanugadgil** [comment]
Hi,
This is indeed a very good question. I have some inputs, in case anyone cares to make a comparison table somewhere.

Folks can chip in information about what  is/is not supported into a table form.

The points mentioned below are not in any particular order, just a few that come to mind

Feature | gobetween | Traefik | Fabio 
--------|-------------|--------|-------
does TCP+SNI (rfc6066) | yes | no | yes
config file syntax | toml, json | toml | configfile key=value
web gui| no | yes | yes
backend discovery mechanisms| consul, exec, docker, etc. | docker, consul, etc.| consul, docker, etc. etc.
publish self into consul |no|yes|yes

**Comment by hbakhtiyor** [comment]
hi, thanks for that table, 

which one of them support load-balancing with session which nginx plus do it?

**Comment by nickdoikov** [comment]
Session based balancing made on L7 OCI level.
Gobetween is a l4 load balancer for now.

**Comment by nickdoikov** [comment]
if there are no objections - i'm closing this issue
