### ISSUE TITLE
[question] multiple SNI using the exec backend

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#84]
Hi,

Using this as reference:
http://gobetween.io/documentation.html#exec

What output would I have to generate if I want one backend IP:PORT to match multiple SNIs.

I know one way would be to use a **regexp** match.

It's not very clear what one would have to do have multiple **exact** matches.

Thanks and Regards,
Shantanu

**Comment by illarion** [comment]
@shantanugadgil did you try to master regexp like this:

`foo|bar|baz`

**Comment by shantanugadgil** [comment]
Oh, silly me. That was so obvious 🤦‍♂️ 
I'll try and let you know if it works out.

**Comment by illarion** [comment]
Well, actually regexp support in sni could have possible issues, so that it is a good test.

**Comment by shantanugadgil** [comment]
@illarion apologies, but I haven't got around to testing this as I had to change my match to `exact` and used `exec`  discovery to emit multiple echo statements.
