### ISSUE TITLE
[request] add support for version flag

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#85]
Hi,
would it be possible to add support for showing the version? Just like `$ go version`
Example:
```
$ gobetween --version
$ gobetween -v
$ gobetween version
```

I tried to find the place where I could try to add this in code myself, but couldn't 😞 

Regards,
Shantanu

**Comment by yyyar** [comment]
@shantanugadgil thanks for the request, it's quite useful indeed. :+1:
