### ISSUE TITLE
Docker single host respond with wildcard ip 0.0.0.0:port

### ISSUE THREAD

**Issue by nickdoikov** [yyyar/gobetween#9]
Instead of swarm that respond with :
```text
ec9ec5753ee2        test1/company:test   "/bin/bash -c 'start   46 hours ago        Up 46 hours         5.5.5.5:39599->9999/tcp, 5.5.5.5:50300->9000/udp,  5.5.5.5:39600->9000/tcp         n1.node.test.com/12121212
```

docker node 
```text
ec9ec5753ee2        test1/company:test   "/bin/bash -c 'start   46 hours ago        Up 46 hours         0.0.0.0:39599->9999/tcp, 0.0.0.0:50300->9000/udp, 0.0.0.0:39600->9000/tcp         n1.node.test.com/12121212
```

So, by default in case of single remote docker host discovery we can`t determine docker containers IP.
It can be fixed in Linux by running : 
```bash
docker run -d -p=192.168.123.138:80:80 tutum/hello-world
```

but under windows we have : 
```text
PS C:\Docker> docker -H tcp://127.0.0.1:2375 run -l proxied=true -d -p 10.0.0.4:8083:80 helloworld
edd0a1ea04851d5d0c817efb2fd3ea0ee6e3f31f89b3fb53a220ab07feead00b
C:\Windows\system32\docker.exe: Error response from daemon: failed to create endpoint hungry_ptolemy on network nat: Windows does not support host IP addresses in NAT settings.

 PS C:\Docker> docker -H tcp://127.0.0.1:2375 run -l proxied=true -d --ip 10.0.0.4 -p 8083:80 helloworld
f4069038a829d617718bc80e4b33fb3a10468fc155b1742dba5319653703650b
C:\Windows\system32\docker.exe: Error response from daemon: User specified IP address is supported on user defined networks only.

```

it needs to eliminate this case for windows compatibility and allow to use linux docker also with wildcard binding

for this we need check does discovery return 0.0.0.0:port and change port with variable : 
docker_binded_host=IP/hostname

**Comment by yyyar** [comment]
algorithm will be:

1. If docker_container_host_env_var is set, try to get host from env var
2. If host from container port mappings is 0.0.0.0, try to parse/infer hostname from docker_endpoint
3. Otherwise, or if everything else fails, return host from ports mapping.
