### ISSUE TITLE
[feature request] show frontend port which is causing the SNI mismatch error

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#98]
Hi,

with respect to:
https://github.com/yyyar/gobetween/commit/5046041d5dcb838fdddb515a7a2a73a9c7338bea

would it be possible to _also_ show the frontend server (i.e. port) for which the SNI mismatch occurred?

edit: sometimes it could happen that there is some mis-configuration (especially with many frontend servers) and then such a message would be helpful, I think.

Regards,
Shantanu

**Comment by shantanugadgil** [comment]
Hi folks, any thoughts/inputs on this. (I am not a Gopher yet, otherwise would have definitely tried my hand at this).

Cheers,
Shantanu

**Comment by yyyar** [comment]
Done in master
